package codegen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"testing"

	shunter "github.com/ponchione/shunter"
	"github.com/ponchione/shunter/schema"
)

func FuzzGenerateTypeScriptFromContractJSON(f *testing.F) {
	for _, seed := range [][]byte{
		nil,
		[]byte("not-json"),
		[]byte(`{"contract_version":0}`),
		mustCodegenFuzzContractJSON(f, contractFixture()),
		mustCodegenFuzzContractJSON(f, codegenIdentifierCollisionFixture()),
		mustCodegenFuzzContractJSON(f, codegenInvalidQuerySQLFixture()),
		mustCodegenFuzzContractJSON(f, codegenUnsupportedColumnTypeFixture()),
	} {
		f.Add(seed)
	}

	const maxCodegenFuzzBytes = 64 << 10
	f.Fuzz(func(t *testing.T, data []byte) {
		if len(data) > maxCodegenFuzzBytes {
			t.Skip("codegen fuzz input above bounded local limit")
		}
		label := codegenFuzzLabel(data, maxCodegenFuzzBytes)

		first, err := GenerateFromJSON(data, Options{Language: LanguageTypeScript})
		if err != nil {
			if !errors.Is(err, ErrInvalidContract) {
				t.Fatalf("%s operation=GenerateFromJSON observed_error=%v expected_wrapped=%v", label, err, ErrInvalidContract)
			}
			return
		}
		if len(first) == 0 {
			t.Fatalf("%s operation=GenerateFromJSON observed_empty_output=true expected=false", label)
		}
		if !bytes.Contains(first, []byte("Code generated by github.com/ponchione/shunter/codegen")) {
			t.Fatalf("%s operation=GenerateFromJSON missing generated header output=%q", label, first)
		}

		second, err := GenerateFromJSON(data, Options{Language: LanguageTypeScript})
		if err != nil {
			t.Fatalf("%s operation=GenerateFromJSONAgain observed_error=%v expected=nil", label, err)
		}
		if !bytes.Equal(first, second) {
			t.Fatalf("%s operation=GenerateDeterminism first=%s second=%s", label, first, second)
		}

		var contract shunter.ModuleContract
		if err := json.Unmarshal(data, &contract); err != nil {
			t.Fatalf("%s operation=UnmarshalAccepted observed_error=%v expected=nil", label, err)
		}
		canonical, err := contract.MarshalCanonicalJSON()
		if err != nil {
			t.Fatalf("%s operation=MarshalCanonicalJSON observed_error=%v expected=nil", label, err)
		}
		fromCanonical, err := GenerateFromJSON(canonical, Options{Language: LanguageTypeScript})
		if err != nil {
			t.Fatalf("%s operation=GenerateFromCanonical observed_error=%v expected=nil canonical=%s", label, err, canonical)
		}
		if !bytes.Equal(first, fromCanonical) {
			t.Fatalf("%s operation=CanonicalInputEquivalence direct=%s canonical=%s", label, first, fromCanonical)
		}
	})
}

func codegenIdentifierCollisionFixture() shunter.ModuleContract {
	contract := contractFixture()
	contract.Schema.Tables[0].Columns[1].Name = "body-text"
	contract.Schema.Tables = append(contract.Schema.Tables, contract.Schema.Tables[0])
	contract.Schema.Tables[1].Name = "live_messages"
	contract.Schema.Tables[1].Columns = []schema.ColumnExport{
		{Name: "class", Type: "string"},
		{Name: "1_count", Type: "uint64"},
	}
	contract.Schema.Tables[1].Indexes = nil
	contract.Schema.Reducers = append(contract.Schema.Reducers,
		contract.Schema.Reducers[0],
		contract.Schema.Reducers[1],
	)
	contract.Schema.Reducers[2].Name = "send-message"
	contract.Schema.Reducers[3].Name = "default"
	contract.Queries = append(contract.Queries, shunter.QueryDescription{Name: "recent-messages"})
	contract.Views = append(contract.Views, shunter.ViewDescription{Name: "live messages"})
	return contract
}

func codegenInvalidQuerySQLFixture() shunter.ModuleContract {
	contract := contractFixture()
	contract.Queries[0].SQL = "SELECT * FROM missing_table"
	return contract
}

func codegenUnsupportedColumnTypeFixture() shunter.ModuleContract {
	contract := contractFixture()
	contract.Schema.Tables[0].Columns[0].Type = "definitely-not-a-shunter-type"
	return contract
}

func mustCodegenFuzzContractJSON(tb testing.TB, contract shunter.ModuleContract) []byte {
	tb.Helper()
	data, err := contract.MarshalCanonicalJSON()
	if err != nil {
		tb.Fatalf("marshal codegen fuzz contract seed: %v", err)
	}
	return data
}

func codegenFuzzLabel(data []byte, maxBytes int) string {
	if len(data) <= 80 {
		return fmt.Sprintf("seed_len=%d seed=%x codegen_config=max_bytes=%d", len(data), data, maxBytes)
	}
	return fmt.Sprintf("seed_len=%d seed_prefix=%x codegen_config=max_bytes=%d", len(data), data[:80], maxBytes)
}
