package codegen

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	shunter "github.com/ponchione/shunter"
	"github.com/ponchione/shunter/protocol"
	"github.com/ponchione/shunter/schema"
)

type namedTypeScriptIdentifier struct {
	name       string
	identifier string
	sql        string
}

type typeScriptTableDecoder struct {
	columnsIdentifier string
	decoderIdentifier string
}

type typeScriptGenerationOptions struct {
	runtimeImport string
}

type typeScriptRuntimeValueImports struct {
	callReducerWithEncodedArgs bool
	callReducerWithResult      bool
	decodeBsatnProduct         bool
	decodeDeclaredQueryResult  bool
	encodeBsatnProduct         bool
}

func generateTypeScript(contract shunter.ModuleContract, opts typeScriptGenerationOptions) ([]byte, error) {
	var b bytes.Buffer

	b.WriteString("// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source contract: %s v%d\n", contract.Codegen.ContractFormat, contract.Codegen.ContractVersion)
	if contract.Module.Name != "" || contract.Module.Version != "" {
		fmt.Fprintf(&b, "// Module: %s %s\n", typeScriptLineCommentText(contract.Module.Name), typeScriptLineCommentText(contract.Module.Version))
	}
	b.WriteString("\n")
	writeTypeScriptRuntimeImports(&b, opts.runtimeImport)
	writeTypeScriptRuntimeValueImports(&b, opts.runtimeImport, typeScriptRuntimeValueImportUsage(contract))
	if err := writeTypeScriptProtocolMetadata(&b); err != nil {
		return nil, err
	}
	writeTypeScriptContractMetadata(&b, contract)
	b.WriteString("export type ReducerCaller = ShunterReducerCaller<ReducerName, Uint8Array, Uint8Array>;\n")
	b.WriteString("export type EncodedReducerCallOptions<Args = unknown> = ShunterEncodedReducerCallOptions<Args>;\n")
	b.WriteString("export type EncodedReducerCallResultOptions<Args = unknown, Result = Uint8Array> = ShunterEncodedReducerCallResultOptions<Args, Result>;\n")
	b.WriteString("export type ReducerCallResult<Name extends ReducerName = ReducerName, Result = Uint8Array> = ShunterReducerCallResult<Name, Result>;\n")
	b.WriteString("export type ReducerCallResultOptions = ShunterReducerCallResultRequestOptions<Uint8Array>;\n")
	b.WriteString("export type QueryRunner = ShunterQueryRunner<Uint8Array>;\n")
	b.WriteString("export type ViewSubscriber = ShunterViewSubscriber;\n")
	b.WriteString("export type DeclaredQueryRunner = ShunterDeclaredQueryRunner<ExecutableQueryName, Uint8Array>;\n")
	b.WriteString("export type DeclaredQueryOptions = ShunterDeclaredQueryOptions;\n")
	b.WriteString("export type DeclaredQueryRunOptions = Omit<DeclaredQueryOptions, \"params\">;\n")
	b.WriteString("export type RawDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName> = ShunterRawDeclaredQueryResult<Name>;\n")
	b.WriteString("export type DeclaredQueryDecodeOptions<RowsByName extends object = TableRows> = ShunterDeclaredQueryDecodeOptions<RowsByName>;\n")
	b.WriteString("export type DeclaredQueryDecodedRunOptions<RowsByName extends object = TableRows> = DeclaredQueryRunOptions & DeclaredQueryDecodeOptions<RowsByName>;\n")
	b.WriteString("export type DecodedDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName, RowsByName extends object = TableRows> = ShunterDecodedDeclaredQueryResult<Name, RowsByName>;\n")
	b.WriteString("export type DeclaredViewSubscriber = ShunterDeclaredViewSubscriber<ExecutableViewName>;\n")
	b.WriteString("export type DeclaredViewHandleSubscriber = ShunterDeclaredViewHandleSubscriber<ExecutableViewName>;\n")
	b.WriteString("export type DeclaredViewSubscriptionOptions<Row = unknown> = Omit<ShunterDeclaredViewSubscriptionOptions<Row>, \"params\">;\n")
	b.WriteString("export type SubscriptionUnsubscribe = ShunterSubscriptionUnsubscribe;\n")
	b.WriteString("export type SubscriptionHandle<Row = unknown> = ShunterSubscriptionHandle<Row>;\n")
	b.WriteString("export type SubscriptionHandleReturnOptions = ShunterSubscriptionHandleReturnOptions;\n")
	b.WriteString("export type TableRow<Name extends TableName> = TableRows[Name];\n")
	b.WriteString("export type TableSubscriber<Row = never> = ShunterTableSubscriber<TableName, TableRows, Row>;\n")
	b.WriteString("export type TableSubscriptionOptions<Row = unknown> = ShunterTableSubscriptionOptions<Row>;\n")
	b.WriteString("export type TableRowDecoder<Name extends TableName> = ShunterTableRowDecoder<TableRows[Name]>;\n")
	b.WriteString("export type TableRowDecoders<RowsByName extends object = TableRows> = ShunterTableRowDecoders<RowsByName>;\n")
	b.WriteString("export type UUID = string;\n")
	b.WriteString("\n")

	tableNames := make([]string, len(contract.Schema.Tables))
	for i, table := range contract.Schema.Tables {
		tableNames[i] = table.Name
	}
	tableTypes := uniqueTypeScriptIdentifiers(tableNames, typeScriptPascalIdentifier)
	tableConstants := uniqueTypeScriptIdentifiers(tableNames, typeScriptCamelIdentifier)
	for i, table := range contract.Schema.Tables {
		rowType := tableTypes[i].identifier + "Row"
		fmt.Fprintf(&b, "export interface %s {\n", rowType)
		columnNames := make([]string, len(table.Columns))
		for j, column := range table.Columns {
			columnNames[j] = column.Name
		}
		columnIdentifiers := uniqueTypeScriptIdentifiers(columnNames, typeScriptCamelIdentifier)
		for j, column := range table.Columns {
			tsType, err := typeScriptColumnType(column.Type)
			if err != nil {
				return nil, err
			}
			if column.Nullable {
				tsType += " | null"
			}
			fmt.Fprintf(&b, "  %s: %s;\n", columnIdentifiers[j].identifier, tsType)
		}
		b.WriteString("}\n\n")
	}

	writeTypeScriptConstMap(&b, "tables", tableConstants)
	b.WriteString("export type TableName = (typeof tables)[keyof typeof tables];\n\n")
	writeTypeScriptTableRows(&b, contract.Schema.Tables, tableTypes)
	topLevelValueNames := typeScriptTopLevelValueNames()
	if _, err := writeTypeScriptTableRowDecoders(&b, contract.Schema.Tables, tableTypes, topLevelValueNames); err != nil {
		return nil, err
	}
	writeTypeScriptTableReadPolicies(&b, contract.Schema.Tables, tableConstants)
	writeTypeScriptVisibilityFilters(&b, contract.VisibilityFilters)
	for i, table := range contract.Schema.Tables {
		rowType := tableTypes[i].identifier + "Row"
		functionName := uniqueTypeScriptIdentifier("subscribe"+tableTypes[i].identifier, topLevelValueNames)
		fmt.Fprintf(&b, "export function %s(subscribeTable: TableSubscriber<%s>, onRows?: (rows: %s[]) => void, options: TableSubscriptionOptions<%s> = {}): Promise<SubscriptionUnsubscribe> {\n", functionName, rowType, rowType, rowType)
		fmt.Fprintf(&b, "  const subscribeOptions: TableSubscriptionOptions<%s> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders[%s] } : options;\n", rowType, strconv.Quote(table.Name))
		fmt.Fprintf(&b, "  return subscribeTable(%s, onRows, subscribeOptions);\n", strconv.Quote(table.Name))
		b.WriteString("}\n\n")
	}

	reducerNames := make([]string, 0, len(contract.Schema.Reducers))
	lifecycleReducerNames := make([]string, 0, len(contract.Schema.Reducers))
	for _, reducer := range contract.Schema.Reducers {
		if reducer.Lifecycle {
			lifecycleReducerNames = append(lifecycleReducerNames, reducer.Name)
			continue
		}
		reducerNames = append(reducerNames, reducer.Name)
	}
	reducerIdentifiers := uniqueTypeScriptIdentifiers(reducerNames, typeScriptCamelIdentifier)
	writeTypeScriptConstMap(&b, "reducers", reducerIdentifiers)
	b.WriteString("export type ReducerName = (typeof reducers)[keyof typeof reducers];\n\n")
	reducersByName := make(map[string]schema.ReducerExport, len(contract.Schema.Reducers))
	for _, reducer := range contract.Schema.Reducers {
		reducersByName[reducer.Name] = reducer
	}
	for _, reducer := range reducerIdentifiers {
		reducerExport := reducersByName[reducer.name]
		var argsTypeName, argsEncoderName string
		if reducerExport.Args != nil {
			argsTypeName = uniqueTypeScriptIdentifier(upperFirst(reducer.identifier)+"Args", topLevelValueNames)
			argsColumnsName := uniqueTypeScriptIdentifier(reducer.identifier+"ArgsColumns", topLevelValueNames)
			argsEncoderName = uniqueTypeScriptIdentifier("encode"+upperFirst(reducer.identifier)+"Args", topLevelValueNames)
			if err := writeTypeScriptProductCodec(&b, argsTypeName, argsColumnsName, argsEncoderName, "", *reducerExport.Args, true, false); err != nil {
				return nil, err
			}
		}
		if reducerExport.Result != nil {
			resultTypeName := uniqueTypeScriptIdentifier(upperFirst(reducer.identifier)+"Result", topLevelValueNames)
			resultColumnsName := uniqueTypeScriptIdentifier(reducer.identifier+"ResultColumns", topLevelValueNames)
			resultDecoderName := uniqueTypeScriptIdentifier("decode"+upperFirst(reducer.identifier)+"Result", topLevelValueNames)
			if err := writeTypeScriptProductCodec(&b, resultTypeName, resultColumnsName, "", resultDecoderName, *reducerExport.Result, false, true); err != nil {
				return nil, err
			}
		}
		functionName := uniqueTypeScriptIdentifier("call"+upperFirst(reducer.identifier), topLevelValueNames)
		fmt.Fprintf(&b, "export function %s(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {\n", functionName)
		fmt.Fprintf(&b, "  return callReducer(%s, args);\n", strconv.Quote(reducer.name))
		b.WriteString("}\n\n")
		if reducerExport.Args != nil {
			typedFunctionName := uniqueTypeScriptIdentifier(functionName+"Typed", topLevelValueNames)
			fmt.Fprintf(&b, "export function %s(callReducer: ReducerCaller, args: %s, options: EncodedReducerCallOptions<%s> = {}): Promise<Uint8Array> {\n", typedFunctionName, argsTypeName, argsTypeName)
			fmt.Fprintf(&b, "  const callOptions: EncodedReducerCallOptions<%s> = options.encodeArgs === undefined ? { ...options, encodeArgs: %s } : options;\n", argsTypeName, argsEncoderName)
			fmt.Fprintf(&b, "  return shunterCallReducerWithEncodedArgs(callReducer, %s, args, callOptions);\n", strconv.Quote(reducer.name))
			b.WriteString("}\n\n")
		}
		resultFunctionName := uniqueTypeScriptIdentifier(functionName+"Result", topLevelValueNames)
		fmt.Fprintf(&b, "export function %s(callReducer: ReducerCaller, args: Uint8Array, options: ReducerCallResultOptions = {}): Promise<ReducerCallResult<typeof reducers.%s>> {\n", resultFunctionName, reducer.identifier)
		fmt.Fprintf(&b, "  return shunterCallReducerWithResult(callReducer, %s, args, options);\n", strconv.Quote(reducer.name))
		b.WriteString("}\n\n")
	}
	lifecycleReducerIdentifiers := uniqueTypeScriptIdentifiers(lifecycleReducerNames, typeScriptLifecycleIdentifier)
	writeTypeScriptConstMap(&b, "lifecycleReducers", lifecycleReducerIdentifiers)
	b.WriteString("export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];\n\n")

	queryNames := make([]string, len(contract.Queries))
	for i, query := range contract.Queries {
		queryNames[i] = query.Name
	}
	queryIdentifiers := uniqueTypeScriptIdentifiers(queryNames, typeScriptCamelIdentifier)
	writeTypeScriptConstMap(&b, "queries", queryIdentifiers)
	b.WriteString("export type QueryName = (typeof queries)[keyof typeof queries];\n\n")
	executableQueries := executableQueryIdentifiers(contract.Queries, queryIdentifiers)
	writeTypeScriptSQLConstMap(&b, "querySQL", executableQueries)
	b.WriteString("export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];\n\n")
	for _, query := range executableQueries {
		queryDescription := contract.Queries[queryIndexByName(contract.Queries, query.name)]
		var queryParamsTypeName, queryParamsEncoderName string
		if typeScriptDeclaredReadHasParameters(queryDescription.Parameters) {
			queryParamsTypeName = uniqueTypeScriptIdentifier(upperFirst(query.identifier)+"Params", topLevelValueNames)
			queryParamsColumnsName := uniqueTypeScriptIdentifier(query.identifier+"ParamColumns", topLevelValueNames)
			queryParamsEncoderName = uniqueTypeScriptIdentifier("encode"+upperFirst(query.identifier)+"Params", topLevelValueNames)
			if err := writeTypeScriptProductCodec(&b, queryParamsTypeName, queryParamsColumnsName, queryParamsEncoderName, "", *queryDescription.Parameters, true, false); err != nil {
				return nil, err
			}
		}
		var queryRowsTypeName, queryRowDecodersName string
		if queryDescription.RowSchema != nil && queryDescription.ResultShape != nil {
			rowTypeName := uniqueTypeScriptIdentifier(upperFirst(query.identifier)+"QueryRow", topLevelValueNames)
			columnsName := uniqueTypeScriptIdentifier(query.identifier+"QueryColumns", topLevelValueNames)
			decoderName := uniqueTypeScriptIdentifier("decode"+upperFirst(query.identifier)+"QueryRow", topLevelValueNames)
			if err := writeTypeScriptProductCodec(&b, rowTypeName, columnsName, "", decoderName, *queryDescription.RowSchema, false, true); err != nil {
				return nil, err
			}
			queryRowsTypeName = uniqueTypeScriptIdentifier(upperFirst(query.identifier)+"QueryRows", topLevelValueNames)
			queryRowDecodersName = uniqueTypeScriptIdentifier(query.identifier+"QueryRowDecoders", topLevelValueNames)
			fmt.Fprintf(&b, "export type %s = {\n", queryRowsTypeName)
			fmt.Fprintf(&b, "  %s: %s;\n", strconv.Quote(queryDescription.ResultShape.Table), rowTypeName)
			b.WriteString("};\n\n")
			fmt.Fprintf(&b, "export const %s = {\n", queryRowDecodersName)
			fmt.Fprintf(&b, "  %s: %s,\n", strconv.Quote(queryDescription.ResultShape.Table), decoderName)
			fmt.Fprintf(&b, "} as const satisfies TableRowDecoders<%s>;\n\n", queryRowsTypeName)
		}
		functionName := uniqueTypeScriptIdentifier("query"+upperFirst(query.identifier), topLevelValueNames)
		if queryParamsTypeName != "" {
			fmt.Fprintf(&b, "export function %s(runDeclaredQuery: DeclaredQueryRunner, params: %s, options: DeclaredQueryRunOptions = {}): Promise<Uint8Array> {\n", functionName, queryParamsTypeName)
			fmt.Fprintf(&b, "  return runDeclaredQuery(%s, { ...options, params: %s(params) });\n", strconv.Quote(query.name), queryParamsEncoderName)
		} else {
			fmt.Fprintf(&b, "export function %s(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {\n", functionName)
			fmt.Fprintf(&b, "  return runDeclaredQuery(%s);\n", strconv.Quote(query.name))
		}
		b.WriteString("}\n\n")
		resultFunctionName := uniqueTypeScriptIdentifier(functionName+"Result", topLevelValueNames)
		if queryRowsTypeName != "" {
			fmt.Fprintf(&b, "export function %s(data: unknown, options: DeclaredQueryDecodeOptions<%s> = {}): DecodedDeclaredQueryResult<typeof queries.%s, %s> {\n", resultFunctionName, queryRowsTypeName, query.identifier, queryRowsTypeName)
			fmt.Fprintf(&b, "  const decodeOptions: DeclaredQueryDecodeOptions<%s> = options.tableDecoders === undefined && options.decodeRow === undefined ? { ...options, tableDecoders: %s } : options;\n", queryRowsTypeName, queryRowDecodersName)
			fmt.Fprintf(&b, "  return shunterDecodeDeclaredQueryResult(%s, data, decodeOptions);\n", strconv.Quote(query.name))
			b.WriteString("}\n\n")
			decodedFunctionName := uniqueTypeScriptIdentifier(functionName+"Decoded", topLevelValueNames)
			if queryParamsTypeName != "" {
				fmt.Fprintf(&b, "export async function %s(runDeclaredQuery: DeclaredQueryRunner, params: %s, options: DeclaredQueryDecodedRunOptions<%s> = {}): Promise<DecodedDeclaredQueryResult<typeof queries.%s, %s>> {\n", decodedFunctionName, queryParamsTypeName, queryRowsTypeName, query.identifier, queryRowsTypeName)
				b.WriteString("  const queryOptions: DeclaredQueryOptions = {\n")
				b.WriteString("    requestId: options.requestId,\n")
				b.WriteString("    messageId: options.messageId,\n")
				b.WriteString("    signal: options.signal,\n")
				fmt.Fprintf(&b, "    params: %s(params),\n", queryParamsEncoderName)
				b.WriteString("  };\n")
				fmt.Fprintf(&b, "  const decodeOptions: DeclaredQueryDecodeOptions<%s> = {\n", queryRowsTypeName)
				b.WriteString("    tableDecoders: options.tableDecoders,\n")
				b.WriteString("    decodeRow: options.decodeRow,\n")
				b.WriteString("  };\n")
				fmt.Fprintf(&b, "  return %s(await runDeclaredQuery(%s, queryOptions), decodeOptions);\n", resultFunctionName, strconv.Quote(query.name))
			} else {
				fmt.Fprintf(&b, "export async function %s(runDeclaredQuery: DeclaredQueryRunner, options: DeclaredQueryDecodeOptions<%s> = {}): Promise<DecodedDeclaredQueryResult<typeof queries.%s, %s>> {\n", decodedFunctionName, queryRowsTypeName, query.identifier, queryRowsTypeName)
				fmt.Fprintf(&b, "  return %s(await runDeclaredQuery(%s), options);\n", resultFunctionName, strconv.Quote(query.name))
			}
			b.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&b, "export function %s<RowsByName extends object = TableRows>(data: unknown, options: DeclaredQueryDecodeOptions<RowsByName>): DecodedDeclaredQueryResult<typeof queries.%s, RowsByName> {\n", resultFunctionName, query.identifier)
			fmt.Fprintf(&b, "  return shunterDecodeDeclaredQueryResult(%s, data, options);\n", strconv.Quote(query.name))
			b.WriteString("}\n\n")
		}
	}

	viewNames := make([]string, len(contract.Views))
	for i, view := range contract.Views {
		viewNames[i] = view.Name
	}
	viewIdentifiers := uniqueTypeScriptIdentifiers(viewNames, typeScriptCamelIdentifier)
	writeTypeScriptConstMap(&b, "views", viewIdentifiers)
	b.WriteString("export type ViewName = (typeof views)[keyof typeof views];\n\n")
	executableViews := executableViewIdentifiers(contract.Views, viewIdentifiers)
	writeTypeScriptSQLConstMap(&b, "viewSQL", executableViews)
	b.WriteString("export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];\n\n")
	for _, view := range executableViews {
		viewDescription := contract.Views[viewIndexByName(contract.Views, view.name)]
		var viewParamsTypeName, viewParamsEncoderName string
		if typeScriptDeclaredReadHasParameters(viewDescription.Parameters) {
			viewParamsTypeName = uniqueTypeScriptIdentifier(upperFirst(view.identifier)+"Params", topLevelValueNames)
			viewParamsColumnsName := uniqueTypeScriptIdentifier(view.identifier+"ParamColumns", topLevelValueNames)
			viewParamsEncoderName = uniqueTypeScriptIdentifier("encode"+upperFirst(view.identifier)+"Params", topLevelValueNames)
			if err := writeTypeScriptProductCodec(&b, viewParamsTypeName, viewParamsColumnsName, viewParamsEncoderName, "", *viewDescription.Parameters, true, false); err != nil {
				return nil, err
			}
		}
		var rowTypeName, decoderName string
		if viewDescription.RowSchema != nil {
			rowTypeName = uniqueTypeScriptIdentifier(upperFirst(view.identifier)+"ViewRow", topLevelValueNames)
			columnsName := uniqueTypeScriptIdentifier(view.identifier+"ViewColumns", topLevelValueNames)
			decoderName = uniqueTypeScriptIdentifier("decode"+upperFirst(view.identifier)+"ViewRow", topLevelValueNames)
			if err := writeTypeScriptProductCodec(&b, rowTypeName, columnsName, "", decoderName, *viewDescription.RowSchema, false, true); err != nil {
				return nil, err
			}
		}
		functionName := uniqueTypeScriptIdentifier("subscribe"+upperFirst(view.identifier), topLevelValueNames)
		if rowTypeName != "" {
			if viewParamsTypeName != "" {
				fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewSubscriber, params: %s, options: DeclaredViewSubscriptionOptions<%s> = {}): Promise<SubscriptionUnsubscribe> {\n", functionName, viewParamsTypeName, rowTypeName)
			} else {
				fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewSubscriber, options: DeclaredViewSubscriptionOptions<%s> = {}): Promise<SubscriptionUnsubscribe> {\n", functionName, rowTypeName)
			}
			fmt.Fprintf(&b, "  const subscribeOptions: DeclaredViewSubscriptionOptions<%s> = options.decodeRow === undefined ? { ...options, decodeRow: %s } : options;\n", rowTypeName, decoderName)
			if viewParamsTypeName != "" {
				fmt.Fprintf(&b, "  return subscribeDeclaredView(%s, { ...subscribeOptions, params: %s(params) });\n", strconv.Quote(view.name), viewParamsEncoderName)
			} else {
				fmt.Fprintf(&b, "  return subscribeDeclaredView(%s, subscribeOptions);\n", strconv.Quote(view.name))
			}
			b.WriteString("}\n\n")
			handleFunctionName := uniqueTypeScriptIdentifier(functionName+"Handle", topLevelValueNames)
			if viewParamsTypeName != "" {
				fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewHandleSubscriber, params: %s, options: DeclaredViewSubscriptionOptions<%s> & SubscriptionHandleReturnOptions): Promise<SubscriptionHandle<%s>> {\n", handleFunctionName, viewParamsTypeName, rowTypeName, rowTypeName)
			} else {
				fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewHandleSubscriber, options: DeclaredViewSubscriptionOptions<%s> & SubscriptionHandleReturnOptions): Promise<SubscriptionHandle<%s>> {\n", handleFunctionName, rowTypeName, rowTypeName)
			}
			fmt.Fprintf(&b, "  const subscribeOptions: DeclaredViewSubscriptionOptions<%s> & SubscriptionHandleReturnOptions = options.decodeRow === undefined ? { ...options, decodeRow: %s } : options;\n", rowTypeName, decoderName)
			if viewParamsTypeName != "" {
				fmt.Fprintf(&b, "  return subscribeDeclaredView(%s, { ...subscribeOptions, params: %s(params) });\n", strconv.Quote(view.name), viewParamsEncoderName)
			} else {
				fmt.Fprintf(&b, "  return subscribeDeclaredView(%s, subscribeOptions);\n", strconv.Quote(view.name))
			}
			b.WriteString("}\n\n")
		} else {
			if viewParamsTypeName != "" {
				fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewSubscriber, params: %s, options: DeclaredViewSubscriptionOptions = {}): Promise<SubscriptionUnsubscribe> {\n", functionName, viewParamsTypeName)
				fmt.Fprintf(&b, "  return subscribeDeclaredView(%s, { ...options, params: %s(params) });\n", strconv.Quote(view.name), viewParamsEncoderName)
			} else {
				fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {\n", functionName)
				fmt.Fprintf(&b, "  return subscribeDeclaredView(%s);\n", strconv.Quote(view.name))
			}
			b.WriteString("}\n\n")
		}
	}

	writeTypeScriptPermissions(&b, contract.Permissions)
	writeTypeScriptReadModels(&b, contract.ReadModel.Declarations)

	return b.Bytes(), nil
}

func typeScriptTopLevelValueNames() map[string]int {
	names := []string{
		"shunterCallReducerWithEncodedArgs",
		"shunterCallReducerWithResult",
		"shunterDecodeBsatnProduct",
		"shunterDecodeDeclaredQueryResult",
		"shunterEncodeBsatnProduct",
		"shunterContract",
		"shunterProtocol",
		"tables",
		"tableRowDecoders",
		"tableReadPolicies",
		"visibilityFilters",
		"reducers",
		"lifecycleReducers",
		"queries",
		"querySQL",
		"views",
		"viewSQL",
		"permissions",
		"readModels",
	}
	seen := make(map[string]int, len(names))
	for _, name := range names {
		seen[name] = 1
	}
	return seen
}

func writeTypeScriptRuntimeImports(b *bytes.Buffer, runtimeImport string) {
	b.WriteString("import type {\n")
	b.WriteString("  BsatnColumn as ShunterBsatnColumn,\n")
	b.WriteString("  DecodedDeclaredQueryResult as ShunterDecodedDeclaredQueryResult,\n")
	b.WriteString("  DeclaredQueryDecodeOptions as ShunterDeclaredQueryDecodeOptions,\n")
	b.WriteString("  DeclaredQueryOptions as ShunterDeclaredQueryOptions,\n")
	b.WriteString("  DeclaredQueryRunner as ShunterDeclaredQueryRunner,\n")
	b.WriteString("  DeclaredViewHandleSubscriber as ShunterDeclaredViewHandleSubscriber,\n")
	b.WriteString("  DeclaredViewSubscriber as ShunterDeclaredViewSubscriber,\n")
	b.WriteString("  DeclaredViewSubscriptionOptions as ShunterDeclaredViewSubscriptionOptions,\n")
	b.WriteString("  EncodedReducerCallOptions as ShunterEncodedReducerCallOptions,\n")
	b.WriteString("  EncodedReducerCallResultOptions as ShunterEncodedReducerCallResultOptions,\n")
	b.WriteString("  GeneratedContractMetadata as ShunterGeneratedContractMetadata,\n")
	b.WriteString("  ProtocolMetadata as ShunterProtocolMetadata,\n")
	b.WriteString("  QueryRunner as ShunterQueryRunner,\n")
	b.WriteString("  RawDeclaredQueryResult as ShunterRawDeclaredQueryResult,\n")
	b.WriteString("  ReducerCaller as ShunterReducerCaller,\n")
	b.WriteString("  ReducerCallResult as ShunterReducerCallResult,\n")
	b.WriteString("  ReducerCallResultRequestOptions as ShunterReducerCallResultRequestOptions,\n")
	b.WriteString("  SubscriptionUnsubscribe as ShunterSubscriptionUnsubscribe,\n")
	b.WriteString("  SubscriptionHandle as ShunterSubscriptionHandle,\n")
	b.WriteString("  SubscriptionHandleReturnOptions as ShunterSubscriptionHandleReturnOptions,\n")
	b.WriteString("  TableRowDecoder as ShunterTableRowDecoder,\n")
	b.WriteString("  TableRowDecoders as ShunterTableRowDecoders,\n")
	b.WriteString("  TableSubscriber as ShunterTableSubscriber,\n")
	b.WriteString("  TableSubscriptionOptions as ShunterTableSubscriptionOptions,\n")
	b.WriteString("  ViewSubscriber as ShunterViewSubscriber,\n")
	fmt.Fprintf(b, "} from %s;\n\n", strconv.Quote(runtimeImport))
}

func typeScriptRuntimeValueImportUsage(contract shunter.ModuleContract) typeScriptRuntimeValueImports {
	var usage typeScriptRuntimeValueImports
	if len(contract.Schema.Tables) > 0 {
		usage.decodeBsatnProduct = true
	}
	for _, reducer := range contract.Schema.Reducers {
		if reducer.Lifecycle {
			continue
		}
		usage.callReducerWithResult = true
		if reducer.Args != nil {
			usage.callReducerWithEncodedArgs = true
			usage.encodeBsatnProduct = true
		}
		if reducer.Result != nil {
			usage.decodeBsatnProduct = true
		}
	}
	for _, query := range contract.Queries {
		if strings.TrimSpace(query.SQL) == "" {
			continue
		}
		usage.decodeDeclaredQueryResult = true
		if typeScriptDeclaredReadHasParameters(query.Parameters) {
			usage.encodeBsatnProduct = true
		}
		if query.RowSchema != nil && query.ResultShape != nil {
			usage.decodeBsatnProduct = true
		}
	}
	for _, view := range contract.Views {
		if strings.TrimSpace(view.SQL) == "" {
			continue
		}
		if typeScriptDeclaredReadHasParameters(view.Parameters) {
			usage.encodeBsatnProduct = true
		}
		if view.RowSchema != nil && view.ResultShape != nil {
			usage.decodeBsatnProduct = true
		}
	}
	return usage
}

func typeScriptDeclaredReadHasParameters(parameters *schema.ProductSchemaExport) bool {
	return parameters != nil && len(parameters.Columns) > 0
}

func writeTypeScriptRuntimeValueImports(b *bytes.Buffer, runtimeImport string, usage typeScriptRuntimeValueImports) {
	if !usage.callReducerWithEncodedArgs &&
		!usage.callReducerWithResult &&
		!usage.decodeBsatnProduct &&
		!usage.decodeDeclaredQueryResult &&
		!usage.encodeBsatnProduct {
		return
	}
	b.WriteString("import {\n")
	if usage.callReducerWithEncodedArgs {
		b.WriteString("  callReducerWithEncodedArgs as shunterCallReducerWithEncodedArgs,\n")
	}
	if usage.callReducerWithResult {
		b.WriteString("  callReducerWithResult as shunterCallReducerWithResult,\n")
	}
	if usage.decodeBsatnProduct {
		b.WriteString("  decodeBsatnProduct as shunterDecodeBsatnProduct,\n")
	}
	if usage.decodeDeclaredQueryResult {
		b.WriteString("  decodeDeclaredQueryResult as shunterDecodeDeclaredQueryResult,\n")
	}
	if usage.encodeBsatnProduct {
		b.WriteString("  encodeBsatnProduct as shunterEncodeBsatnProduct,\n")
	}
	fmt.Fprintf(b, "} from %s;\n\n", strconv.Quote(runtimeImport))
}

func writeTypeScriptProtocolMetadata(b *bytes.Buffer) error {
	defaultSubprotocol, ok := protocol.SubprotocolForVersion(protocol.CurrentProtocolVersion)
	if !ok {
		return fmt.Errorf("missing subprotocol for current protocol version %s", protocol.CurrentProtocolVersion)
	}
	b.WriteString("export const shunterProtocol = {\n")
	fmt.Fprintf(b, "  minSupportedVersion: %d,\n", protocol.MinSupportedProtocolVersion)
	fmt.Fprintf(b, "  currentVersion: %d,\n", protocol.CurrentProtocolVersion)
	fmt.Fprintf(b, "  defaultSubprotocol: %s,\n", strconv.Quote(defaultSubprotocol))
	fmt.Fprintf(b, "  supportedSubprotocols: %s,\n", typeScriptStringArray(protocol.SupportedSubprotocols()))
	b.WriteString("} as const satisfies ShunterProtocolMetadata;\n\n")
	b.WriteString("export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];\n\n")
	return nil
}

func writeTypeScriptContractMetadata(b *bytes.Buffer, contract shunter.ModuleContract) {
	b.WriteString("export const shunterContract = {\n")
	fmt.Fprintf(b, "  contractFormat: %s,\n", strconv.Quote(contract.Codegen.ContractFormat))
	fmt.Fprintf(b, "  contractVersion: %d,\n", contract.Codegen.ContractVersion)
	fmt.Fprintf(b, "  moduleName: %s,\n", strconv.Quote(contract.Module.Name))
	fmt.Fprintf(b, "  moduleVersion: %s,\n", strconv.Quote(contract.Module.Version))
	b.WriteString("  protocol: shunterProtocol,\n")
	b.WriteString("} as const satisfies ShunterGeneratedContractMetadata<typeof shunterProtocol>;\n\n")
}

func writeTypeScriptConstMap(b *bytes.Buffer, name string, identifiers []namedTypeScriptIdentifier) {
	fmt.Fprintf(b, "export const %s = {\n", name)
	for _, identifier := range identifiers {
		fmt.Fprintf(b, "  %s: %s,\n", identifier.identifier, strconv.Quote(identifier.name))
	}
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptSQLConstMap(b *bytes.Buffer, name string, identifiers []namedTypeScriptIdentifier) {
	fmt.Fprintf(b, "export const %s = {\n", name)
	for _, identifier := range identifiers {
		fmt.Fprintf(b, "  %s: %s,\n", identifier.identifier, strconv.Quote(identifier.sql))
	}
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptTableRows(b *bytes.Buffer, tables []schema.TableExport, rowTypes []namedTypeScriptIdentifier) {
	b.WriteString("export type TableRows = {\n")
	for i, table := range tables {
		fmt.Fprintf(b, "  %s: %sRow;\n", strconv.Quote(table.Name), rowTypes[i].identifier)
	}
	b.WriteString("};\n\n")
}

func writeTypeScriptTableRowDecoders(b *bytes.Buffer, tables []schema.TableExport, rowTypes []namedTypeScriptIdentifier, topLevelValueNames map[string]int) ([]typeScriptTableDecoder, error) {
	decoders := make([]typeScriptTableDecoder, len(tables))
	for i, table := range tables {
		rowName := rowTypes[i].identifier + "Row"
		columnsName := uniqueTypeScriptIdentifier(lowerFirst(rowTypes[i].identifier)+"Columns", topLevelValueNames)
		decoderName := uniqueTypeScriptIdentifier("decode"+rowTypes[i].identifier+"Row", topLevelValueNames)
		decoders[i] = typeScriptTableDecoder{
			columnsIdentifier: columnsName,
			decoderIdentifier: decoderName,
		}

		fmt.Fprintf(b, "const %s = [\n", columnsName)
		for _, column := range table.Columns {
			if _, err := typeScriptColumnType(column.Type); err != nil {
				return nil, err
			}
			fmt.Fprintf(b, "  { name: %s, kind: %s", strconv.Quote(column.Name), strconv.Quote(column.Type))
			if column.Nullable {
				b.WriteString(", nullable: true")
			}
			b.WriteString(" },\n")
		}
		b.WriteString("] as const satisfies readonly ShunterBsatnColumn[];\n\n")

		columnNames := make([]string, len(table.Columns))
		for j, column := range table.Columns {
			columnNames[j] = column.Name
		}
		columnIdentifiers := uniqueTypeScriptIdentifiers(columnNames, typeScriptCamelIdentifier)
		fmt.Fprintf(b, "export function %s(row: Uint8Array): %s {\n", decoderName, rowName)
		fmt.Fprintf(b, "  return shunterDecodeBsatnProduct(row, %s, (values) => ({\n", columnsName)
		for j, column := range table.Columns {
			tsType, err := typeScriptColumnType(column.Type)
			if err != nil {
				return nil, err
			}
			if column.Nullable {
				tsType += " | null"
			}
			fmt.Fprintf(b, "    %s: values[%d] as %s,\n", columnIdentifiers[j].identifier, j, tsType)
		}
		b.WriteString("  }));\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("export const tableRowDecoders = {\n")
	for i := range tables {
		fmt.Fprintf(b, "  %s: %s,\n", strconv.Quote(tables[i].Name), decoders[i].decoderIdentifier)
	}
	b.WriteString("} as const satisfies TableRowDecoders;\n\n")
	return decoders, nil
}

func writeTypeScriptProductCodec(b *bytes.Buffer, typeName, columnsName, encoderName, decoderName string, product schema.ProductSchemaExport, writeEncoder bool, writeDecoder bool) error {
	columnNames := make([]string, len(product.Columns))
	for i, column := range product.Columns {
		columnNames[i] = column.Name
	}
	columnIdentifiers := uniqueTypeScriptIdentifiers(columnNames, typeScriptCamelIdentifier)

	fmt.Fprintf(b, "export interface %s {\n", typeName)
	for i, column := range product.Columns {
		tsType, err := typeScriptColumnType(column.Type)
		if err != nil {
			return err
		}
		if column.Nullable {
			tsType += " | null"
		}
		fmt.Fprintf(b, "  %s: %s;\n", columnIdentifiers[i].identifier, tsType)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "const %s = [\n", columnsName)
	for _, column := range product.Columns {
		if _, err := typeScriptColumnType(column.Type); err != nil {
			return err
		}
		fmt.Fprintf(b, "  { name: %s, kind: %s", strconv.Quote(column.Name), strconv.Quote(column.Type))
		if column.Nullable {
			b.WriteString(", nullable: true")
		}
		b.WriteString(" },\n")
	}
	b.WriteString("] as const satisfies readonly ShunterBsatnColumn[];\n\n")

	if writeEncoder {
		fmt.Fprintf(b, "export function %s(value: %s): Uint8Array {\n", encoderName, typeName)
		fmt.Fprintf(b, "  return shunterEncodeBsatnProduct([\n")
		for _, identifier := range columnIdentifiers {
			fmt.Fprintf(b, "    value.%s,\n", identifier.identifier)
		}
		fmt.Fprintf(b, "  ], %s);\n", columnsName)
		b.WriteString("}\n\n")
	}

	if writeDecoder {
		fmt.Fprintf(b, "export function %s(row: Uint8Array): %s {\n", decoderName, typeName)
		fmt.Fprintf(b, "  return shunterDecodeBsatnProduct(row, %s, (values) => ({\n", columnsName)
		for i, column := range product.Columns {
			tsType, err := typeScriptColumnType(column.Type)
			if err != nil {
				return err
			}
			if column.Nullable {
				tsType += " | null"
			}
			fmt.Fprintf(b, "    %s: values[%d] as %s,\n", columnIdentifiers[i].identifier, i, tsType)
		}
		b.WriteString("  }));\n")
		b.WriteString("}\n\n")
	}

	return nil
}

func writeTypeScriptTableReadPolicies(b *bytes.Buffer, tables []schema.TableExport, identifiers []namedTypeScriptIdentifier) {
	b.WriteString("export const tableReadPolicies = {\n")
	for i, table := range tables {
		fmt.Fprintf(
			b,
			"  %s: { access: %s, permissions: %s },\n",
			identifiers[i].identifier,
			strconv.Quote(table.ReadPolicy.Access.String()),
			typeScriptStringArray(table.ReadPolicy.Permissions),
		)
	}
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptVisibilityFilters(b *bytes.Buffer, filters []shunter.VisibilityFilterDescription) {
	b.WriteString("export const visibilityFilters = {\n")
	identifiers := visibilityFilterTypeScriptIdentifiers(filters)
	for i, identifier := range identifiers {
		filter := filters[i]
		fmt.Fprintf(
			b,
			"  %s: { sql: %s, returnTable: %s, returnTableId: %d, usesCallerIdentity: %t },\n",
			identifier.identifier,
			strconv.Quote(filter.SQL),
			strconv.Quote(filter.ReturnTable),
			filter.ReturnTableID,
			filter.UsesCallerIdentity,
		)
	}
	b.WriteString("} as const;\n\n")
}

func executableQueryIdentifiers(queries []shunter.QueryDescription, identifiers []namedTypeScriptIdentifier) []namedTypeScriptIdentifier {
	out := make([]namedTypeScriptIdentifier, 0, len(queries))
	for i, query := range queries {
		if strings.TrimSpace(query.SQL) == "" {
			continue
		}
		identifier := identifiers[i]
		identifier.sql = query.SQL
		out = append(out, identifier)
	}
	return out
}

func queryIndexByName(queries []shunter.QueryDescription, name string) int {
	for i, query := range queries {
		if query.Name == name {
			return i
		}
	}
	return -1
}

func executableViewIdentifiers(views []shunter.ViewDescription, identifiers []namedTypeScriptIdentifier) []namedTypeScriptIdentifier {
	out := make([]namedTypeScriptIdentifier, 0, len(views))
	for i, view := range views {
		if strings.TrimSpace(view.SQL) == "" {
			continue
		}
		identifier := identifiers[i]
		identifier.sql = view.SQL
		out = append(out, identifier)
	}
	return out
}

func viewIndexByName(views []shunter.ViewDescription, name string) int {
	for i, view := range views {
		if view.Name == name {
			return i
		}
	}
	return -1
}

func writeTypeScriptPermissions(b *bytes.Buffer, permissions shunter.PermissionContract) {
	b.WriteString("export const permissions = {\n")
	writeTypeScriptPermissionCategory(b, "reducers", permissions.Reducers)
	writeTypeScriptPermissionCategory(b, "queries", permissions.Queries)
	writeTypeScriptPermissionCategory(b, "views", permissions.Views)
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptPermissionCategory(b *bytes.Buffer, category string, declarations []shunter.PermissionContractDeclaration) {
	fmt.Fprintf(b, "  %s: {\n", category)
	identifiers := permissionTypeScriptIdentifiers(declarations)
	for i, identifier := range identifiers {
		fmt.Fprintf(b, "    %s: { required: %s },\n", identifier.identifier, typeScriptStringArray(declarations[i].Required))
	}
	b.WriteString("  },\n")
}

func permissionTypeScriptIdentifiers(declarations []shunter.PermissionContractDeclaration) []namedTypeScriptIdentifier {
	names := make([]string, len(declarations))
	for i, declaration := range declarations {
		names[i] = declaration.Name
	}
	return uniqueTypeScriptIdentifiers(names, typeScriptCamelIdentifier)
}

func writeTypeScriptReadModels(b *bytes.Buffer, declarations []shunter.ReadModelContractDeclaration) {
	b.WriteString("export const readModels = {\n")
	writeTypeScriptReadModelCategory(b, "queries", declarations, shunter.ReadModelSurfaceQuery)
	writeTypeScriptReadModelCategory(b, "views", declarations, shunter.ReadModelSurfaceView)
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptReadModelCategory(b *bytes.Buffer, category string, declarations []shunter.ReadModelContractDeclaration, surface string) {
	filtered := make([]shunter.ReadModelContractDeclaration, 0, len(declarations))
	for _, declaration := range declarations {
		if declaration.Surface == surface {
			filtered = append(filtered, declaration)
		}
	}

	fmt.Fprintf(b, "  %s: {\n", category)
	identifiers := readModelTypeScriptIdentifiers(filtered)
	for i, identifier := range identifiers {
		declaration := filtered[i]
		fmt.Fprintf(
			b,
			"    %s: { tables: %s, tags: %s },\n",
			identifier.identifier,
			typeScriptStringArray(declaration.Tables),
			typeScriptStringArray(declaration.Tags),
		)
	}
	b.WriteString("  },\n")
}

func readModelTypeScriptIdentifiers(declarations []shunter.ReadModelContractDeclaration) []namedTypeScriptIdentifier {
	names := make([]string, len(declarations))
	for i, declaration := range declarations {
		names[i] = declaration.Name
	}
	return uniqueTypeScriptIdentifiers(names, typeScriptCamelIdentifier)
}

func visibilityFilterTypeScriptIdentifiers(filters []shunter.VisibilityFilterDescription) []namedTypeScriptIdentifier {
	names := make([]string, len(filters))
	for i, filter := range filters {
		names[i] = filter.Name
	}
	return uniqueTypeScriptIdentifiers(names, typeScriptCamelIdentifier)
}

func typeScriptStringArray(values []string) string {
	if len(values) == 0 {
		return "[]"
	}
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = strconv.Quote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

var typeScriptLineCommentEscaper = strings.NewReplacer(
	"\r", `\r`,
	"\n", `\n`,
	"\u2028", `\u2028`,
	"\u2029", `\u2029`,
)

func typeScriptLineCommentText(value string) string {
	return typeScriptLineCommentEscaper.Replace(value)
}

func typeScriptColumnType(kind string) (string, error) {
	switch kind {
	case "bool":
		return "boolean", nil
	case "int8", "uint8", "int16", "uint16", "int32", "uint32", "float32", "float64":
		return "number", nil
	case "int64", "uint64", "int128", "uint128", "int256", "uint256", "timestamp", "duration":
		return "bigint", nil
	case "string":
		return "string", nil
	case "uuid":
		return "UUID", nil
	case "bytes":
		return "Uint8Array", nil
	case "arrayString":
		return "string[]", nil
	case "json":
		return "unknown", nil
	default:
		return "", fmt.Errorf("unsupported column type %q", kind)
	}
}

func uniqueTypeScriptIdentifiers(names []string, style func(string) string) []namedTypeScriptIdentifier {
	out := make([]namedTypeScriptIdentifier, len(names))
	seen := make(map[string]int, len(names))
	for i, name := range names {
		base := style(name)
		if base == "" {
			base = "_"
		}
		identifier := uniqueTypeScriptIdentifier(base, seen)
		out[i] = namedTypeScriptIdentifier{name: name, identifier: identifier}
	}
	return out
}

func uniqueTypeScriptIdentifier(base string, seen map[string]int) string {
	identifier := base
	if count := seen[identifier]; count > 0 {
		for suffix := count + 1; ; suffix++ {
			candidate := fmt.Sprintf("%s%d", base, suffix)
			if seen[candidate] == 0 {
				identifier = candidate
				break
			}
		}
	}
	seen[identifier]++
	return identifier
}

func typeScriptCamelIdentifier(name string) string {
	words, hadSeparator := identifierWords(name)
	if len(words) == 0 {
		return "_"
	}
	var b strings.Builder
	for i, word := range words {
		normalized := normalizeIdentifierWord(word)
		if i == 0 {
			if hadSeparator {
				normalized = lowerFirst(normalized)
			}
			b.WriteString(normalized)
			continue
		}
		b.WriteString(upperFirst(normalized))
	}
	return ensureTypeScriptIdentifier(b.String())
}

func typeScriptPascalIdentifier(name string) string {
	words, _ := identifierWords(name)
	if len(words) == 0 {
		return "_"
	}
	var b strings.Builder
	for _, word := range words {
		b.WriteString(upperFirst(normalizeIdentifierWord(word)))
	}
	return ensureTypeScriptIdentifier(b.String())
}

func typeScriptLifecycleIdentifier(name string) string {
	return ensureTypeScriptIdentifier(typeScriptPascalIdentifier(name))
}

func identifierWords(name string) ([]string, bool) {
	var words []string
	var b strings.Builder
	hadSeparator := false
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			continue
		}
		hadSeparator = true
		if b.Len() > 0 {
			words = append(words, b.String())
			b.Reset()
		}
	}
	if b.Len() > 0 {
		words = append(words, b.String())
	}
	return words, hadSeparator
}

func normalizeIdentifierWord(word string) string {
	if word == "" {
		return ""
	}
	if isAllUpperOrDigit(word) || isAllLowerOrDigit(word) {
		return strings.ToLower(word)
	}
	return word
}

func ensureTypeScriptIdentifier(identifier string) string {
	if identifier == "" {
		return "_"
	}
	var b strings.Builder
	for i, r := range identifier {
		if i == 0 && unicode.IsDigit(r) {
			b.WriteRune('_')
			b.WriteRune(r)
			continue
		}
		valid := r == '_' || r == '$' || unicode.IsLetter(r) || unicode.IsDigit(r)
		if !valid {
			b.WriteRune('_')
			continue
		}
		b.WriteRune(r)
	}
	out := b.String()
	if out == "" {
		return "_"
	}
	if typeScriptReservedWords[out] {
		return out + "_"
	}
	return out
}

func upperFirst(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func isAllUpperOrDigit(s string) bool {
	hasLetter := false
	for _, r := range s {
		if !unicode.IsLetter(r) {
			continue
		}
		hasLetter = true
		if unicode.IsLower(r) {
			return false
		}
	}
	return hasLetter
}

func isAllLowerOrDigit(s string) bool {
	hasLetter := false
	for _, r := range s {
		if !unicode.IsLetter(r) {
			continue
		}
		hasLetter = true
		if unicode.IsUpper(r) {
			return false
		}
	}
	return hasLetter
}

var typeScriptReservedWords = map[string]bool{
	"break":      true,
	"case":       true,
	"catch":      true,
	"class":      true,
	"const":      true,
	"continue":   true,
	"debugger":   true,
	"default":    true,
	"delete":     true,
	"do":         true,
	"else":       true,
	"enum":       true,
	"export":     true,
	"extends":    true,
	"false":      true,
	"finally":    true,
	"for":        true,
	"function":   true,
	"if":         true,
	"import":     true,
	"in":         true,
	"instanceof": true,
	"new":        true,
	"null":       true,
	"return":     true,
	"super":      true,
	"switch":     true,
	"this":       true,
	"throw":      true,
	"true":       true,
	"try":        true,
	"typeof":     true,
	"var":        true,
	"void":       true,
	"while":      true,
	"with":       true,
}
