package codegen

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"unicode"

	shunter "github.com/ponchione/shunter"
	"github.com/ponchione/shunter/protocol"
	"github.com/ponchione/shunter/schema"
)

type namedTypeScriptIdentifier struct {
	name       string
	identifier string
	sql        string
}

func generateTypeScript(contract shunter.ModuleContract) ([]byte, error) {
	var b bytes.Buffer

	b.WriteString("// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source contract: %s v%d\n", contract.Codegen.ContractFormat, contract.Codegen.ContractVersion)
	if contract.Module.Name != "" || contract.Module.Version != "" {
		fmt.Fprintf(&b, "// Module: %s %s\n", typeScriptLineCommentText(contract.Module.Name), typeScriptLineCommentText(contract.Module.Version))
	}
	b.WriteString("\n")
	if err := writeTypeScriptProtocolMetadata(&b); err != nil {
		return nil, err
	}
	b.WriteString("export type ReducerCaller = (name: string, args: Uint8Array) => Promise<Uint8Array>;\n")
	b.WriteString("export type QueryRunner = (sql: string) => Promise<Uint8Array>;\n")
	b.WriteString("export type ViewSubscriber = (sql: string) => Promise<() => void>;\n")
	b.WriteString("export type DeclaredQueryRunner = (name: string) => Promise<Uint8Array>;\n")
	b.WriteString("export type DeclaredViewSubscriber = (name: string) => Promise<() => void>;\n")
	b.WriteString("export type TableSubscriber<Row> = (table: string, onRows?: (rows: Row[]) => void) => Promise<() => void>;\n")
	b.WriteString("export type UUID = string;\n")
	b.WriteString("\n")

	tableNames := make([]string, len(contract.Schema.Tables))
	for i, table := range contract.Schema.Tables {
		tableNames[i] = table.Name
	}
	tableTypes := uniqueTypeScriptIdentifiers(tableNames, typeScriptPascalIdentifier)
	tableConstants := uniqueTypeScriptIdentifiers(tableNames, typeScriptCamelIdentifier)
	for i, table := range contract.Schema.Tables {
		rowType := tableTypes[i].identifier + "Row"
		fmt.Fprintf(&b, "export interface %s {\n", rowType)
		columnNames := make([]string, len(table.Columns))
		for j, column := range table.Columns {
			columnNames[j] = column.Name
		}
		columnIdentifiers := uniqueTypeScriptIdentifiers(columnNames, typeScriptCamelIdentifier)
		for j, column := range table.Columns {
			tsType, err := typeScriptColumnType(column.Type)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&b, "  %s: %s;\n", columnIdentifiers[j].identifier, tsType)
		}
		b.WriteString("}\n\n")
	}

	writeTypeScriptConstMap(&b, "tables", tableConstants)
	b.WriteString("export type TableName = (typeof tables)[keyof typeof tables];\n\n")
	writeTypeScriptTableReadPolicies(&b, contract.Schema.Tables, tableConstants)
	writeTypeScriptVisibilityFilters(&b, contract.VisibilityFilters)
	subscribeFunctionNames := make(map[string]int, len(contract.Schema.Tables)+len(contract.Views))
	for i, table := range contract.Schema.Tables {
		rowType := tableTypes[i].identifier + "Row"
		functionName := uniqueTypeScriptIdentifier("subscribe"+tableTypes[i].identifier, subscribeFunctionNames)
		fmt.Fprintf(&b, "export function %s(subscribeTable: TableSubscriber<%s>): Promise<() => void> {\n", functionName, rowType)
		fmt.Fprintf(&b, "  return subscribeTable(%s);\n", strconv.Quote(table.Name))
		b.WriteString("}\n\n")
	}

	reducerNames := make([]string, 0, len(contract.Schema.Reducers))
	lifecycleReducerNames := make([]string, 0, len(contract.Schema.Reducers))
	for _, reducer := range contract.Schema.Reducers {
		if reducer.Lifecycle {
			lifecycleReducerNames = append(lifecycleReducerNames, reducer.Name)
			continue
		}
		reducerNames = append(reducerNames, reducer.Name)
	}
	reducerIdentifiers := uniqueTypeScriptIdentifiers(reducerNames, typeScriptCamelIdentifier)
	writeTypeScriptConstMap(&b, "reducers", reducerIdentifiers)
	b.WriteString("export type ReducerName = (typeof reducers)[keyof typeof reducers];\n\n")
	for _, reducer := range reducerIdentifiers {
		functionName := "call" + upperFirst(reducer.identifier)
		fmt.Fprintf(&b, "export function %s(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {\n", functionName)
		fmt.Fprintf(&b, "  return callReducer(%s, args);\n", strconv.Quote(reducer.name))
		b.WriteString("}\n\n")
	}
	lifecycleReducerIdentifiers := uniqueTypeScriptIdentifiers(lifecycleReducerNames, typeScriptLifecycleIdentifier)
	writeTypeScriptConstMap(&b, "lifecycleReducers", lifecycleReducerIdentifiers)
	b.WriteString("export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];\n\n")

	queryNames := make([]string, len(contract.Queries))
	for i, query := range contract.Queries {
		queryNames[i] = query.Name
	}
	queryIdentifiers := uniqueTypeScriptIdentifiers(queryNames, typeScriptCamelIdentifier)
	writeTypeScriptConstMap(&b, "queries", queryIdentifiers)
	b.WriteString("export type QueryName = (typeof queries)[keyof typeof queries];\n\n")
	executableQueries := executableQueryIdentifiers(contract.Queries, queryIdentifiers)
	writeTypeScriptSQLConstMap(&b, "querySQL", executableQueries)
	b.WriteString("export type ExecutableQueryName = keyof typeof querySQL;\n\n")
	for _, query := range executableQueries {
		functionName := "query" + upperFirst(query.identifier)
		fmt.Fprintf(&b, "export function %s(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {\n", functionName)
		fmt.Fprintf(&b, "  return runDeclaredQuery(%s);\n", strconv.Quote(query.name))
		b.WriteString("}\n\n")
	}

	viewNames := make([]string, len(contract.Views))
	for i, view := range contract.Views {
		viewNames[i] = view.Name
	}
	viewIdentifiers := uniqueTypeScriptIdentifiers(viewNames, typeScriptCamelIdentifier)
	writeTypeScriptConstMap(&b, "views", viewIdentifiers)
	b.WriteString("export type ViewName = (typeof views)[keyof typeof views];\n\n")
	executableViews := executableViewIdentifiers(contract.Views, viewIdentifiers)
	writeTypeScriptSQLConstMap(&b, "viewSQL", executableViews)
	b.WriteString("export type ExecutableViewName = keyof typeof viewSQL;\n\n")
	for _, view := range executableViews {
		functionName := uniqueTypeScriptIdentifier("subscribe"+upperFirst(view.identifier), subscribeFunctionNames)
		fmt.Fprintf(&b, "export function %s(subscribeDeclaredView: DeclaredViewSubscriber): Promise<() => void> {\n", functionName)
		fmt.Fprintf(&b, "  return subscribeDeclaredView(%s);\n", strconv.Quote(view.name))
		b.WriteString("}\n\n")
	}

	writeTypeScriptPermissions(&b, contract.Permissions)
	writeTypeScriptReadModels(&b, contract.ReadModel.Declarations)

	return b.Bytes(), nil
}

func writeTypeScriptProtocolMetadata(b *bytes.Buffer) error {
	defaultSubprotocol, ok := protocol.SubprotocolForVersion(protocol.CurrentProtocolVersion)
	if !ok {
		return fmt.Errorf("missing subprotocol for current protocol version %s", protocol.CurrentProtocolVersion)
	}
	b.WriteString("export const shunterProtocol = {\n")
	fmt.Fprintf(b, "  minSupportedVersion: %d,\n", protocol.MinSupportedProtocolVersion)
	fmt.Fprintf(b, "  currentVersion: %d,\n", protocol.CurrentProtocolVersion)
	fmt.Fprintf(b, "  defaultSubprotocol: %s,\n", strconv.Quote(defaultSubprotocol))
	fmt.Fprintf(b, "  supportedSubprotocols: %s,\n", typeScriptStringArray(protocol.SupportedSubprotocols()))
	b.WriteString("} as const;\n\n")
	b.WriteString("export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];\n\n")
	return nil
}

func writeTypeScriptConstMap(b *bytes.Buffer, name string, identifiers []namedTypeScriptIdentifier) {
	fmt.Fprintf(b, "export const %s = {\n", name)
	for _, identifier := range identifiers {
		fmt.Fprintf(b, "  %s: %s,\n", identifier.identifier, strconv.Quote(identifier.name))
	}
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptSQLConstMap(b *bytes.Buffer, name string, identifiers []namedTypeScriptIdentifier) {
	fmt.Fprintf(b, "export const %s = {\n", name)
	for _, identifier := range identifiers {
		fmt.Fprintf(b, "  %s: %s,\n", identifier.identifier, strconv.Quote(identifier.sql))
	}
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptTableReadPolicies(b *bytes.Buffer, tables []schema.TableExport, identifiers []namedTypeScriptIdentifier) {
	b.WriteString("export const tableReadPolicies = {\n")
	for i, table := range tables {
		fmt.Fprintf(
			b,
			"  %s: { access: %s, permissions: %s },\n",
			identifiers[i].identifier,
			strconv.Quote(table.ReadPolicy.Access.String()),
			typeScriptStringArray(table.ReadPolicy.Permissions),
		)
	}
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptVisibilityFilters(b *bytes.Buffer, filters []shunter.VisibilityFilterDescription) {
	b.WriteString("export const visibilityFilters = {\n")
	identifiers := visibilityFilterTypeScriptIdentifiers(filters)
	for i, identifier := range identifiers {
		filter := filters[i]
		fmt.Fprintf(
			b,
			"  %s: { sql: %s, returnTable: %s, returnTableId: %d, usesCallerIdentity: %t },\n",
			identifier.identifier,
			strconv.Quote(filter.SQL),
			strconv.Quote(filter.ReturnTable),
			filter.ReturnTableID,
			filter.UsesCallerIdentity,
		)
	}
	b.WriteString("} as const;\n\n")
}

func executableQueryIdentifiers(queries []shunter.QueryDescription, identifiers []namedTypeScriptIdentifier) []namedTypeScriptIdentifier {
	out := make([]namedTypeScriptIdentifier, 0, len(queries))
	for i, query := range queries {
		if strings.TrimSpace(query.SQL) == "" {
			continue
		}
		identifier := identifiers[i]
		identifier.sql = query.SQL
		out = append(out, identifier)
	}
	return out
}

func executableViewIdentifiers(views []shunter.ViewDescription, identifiers []namedTypeScriptIdentifier) []namedTypeScriptIdentifier {
	out := make([]namedTypeScriptIdentifier, 0, len(views))
	for i, view := range views {
		if strings.TrimSpace(view.SQL) == "" {
			continue
		}
		identifier := identifiers[i]
		identifier.sql = view.SQL
		out = append(out, identifier)
	}
	return out
}

func writeTypeScriptPermissions(b *bytes.Buffer, permissions shunter.PermissionContract) {
	b.WriteString("export const permissions = {\n")
	writeTypeScriptPermissionCategory(b, "reducers", permissions.Reducers)
	writeTypeScriptPermissionCategory(b, "queries", permissions.Queries)
	writeTypeScriptPermissionCategory(b, "views", permissions.Views)
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptPermissionCategory(b *bytes.Buffer, category string, declarations []shunter.PermissionContractDeclaration) {
	fmt.Fprintf(b, "  %s: {\n", category)
	identifiers := permissionTypeScriptIdentifiers(declarations)
	for i, identifier := range identifiers {
		fmt.Fprintf(b, "    %s: { required: %s },\n", identifier.identifier, typeScriptStringArray(declarations[i].Required))
	}
	b.WriteString("  },\n")
}

func permissionTypeScriptIdentifiers(declarations []shunter.PermissionContractDeclaration) []namedTypeScriptIdentifier {
	names := make([]string, len(declarations))
	for i, declaration := range declarations {
		names[i] = declaration.Name
	}
	return uniqueTypeScriptIdentifiers(names, typeScriptCamelIdentifier)
}

func writeTypeScriptReadModels(b *bytes.Buffer, declarations []shunter.ReadModelContractDeclaration) {
	b.WriteString("export const readModels = {\n")
	writeTypeScriptReadModelCategory(b, "queries", declarations, shunter.ReadModelSurfaceQuery)
	writeTypeScriptReadModelCategory(b, "views", declarations, shunter.ReadModelSurfaceView)
	b.WriteString("} as const;\n\n")
}

func writeTypeScriptReadModelCategory(b *bytes.Buffer, category string, declarations []shunter.ReadModelContractDeclaration, surface string) {
	filtered := make([]shunter.ReadModelContractDeclaration, 0, len(declarations))
	for _, declaration := range declarations {
		if declaration.Surface == surface {
			filtered = append(filtered, declaration)
		}
	}

	fmt.Fprintf(b, "  %s: {\n", category)
	identifiers := readModelTypeScriptIdentifiers(filtered)
	for i, identifier := range identifiers {
		declaration := filtered[i]
		fmt.Fprintf(
			b,
			"    %s: { tables: %s, tags: %s },\n",
			identifier.identifier,
			typeScriptStringArray(declaration.Tables),
			typeScriptStringArray(declaration.Tags),
		)
	}
	b.WriteString("  },\n")
}

func readModelTypeScriptIdentifiers(declarations []shunter.ReadModelContractDeclaration) []namedTypeScriptIdentifier {
	names := make([]string, len(declarations))
	for i, declaration := range declarations {
		names[i] = declaration.Name
	}
	return uniqueTypeScriptIdentifiers(names, typeScriptCamelIdentifier)
}

func visibilityFilterTypeScriptIdentifiers(filters []shunter.VisibilityFilterDescription) []namedTypeScriptIdentifier {
	names := make([]string, len(filters))
	for i, filter := range filters {
		names[i] = filter.Name
	}
	return uniqueTypeScriptIdentifiers(names, typeScriptCamelIdentifier)
}

func typeScriptStringArray(values []string) string {
	if len(values) == 0 {
		return "[]"
	}
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = strconv.Quote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

var typeScriptLineCommentEscaper = strings.NewReplacer(
	"\r", `\r`,
	"\n", `\n`,
	"\u2028", `\u2028`,
	"\u2029", `\u2029`,
)

func typeScriptLineCommentText(value string) string {
	return typeScriptLineCommentEscaper.Replace(value)
}

func typeScriptColumnType(kind string) (string, error) {
	switch kind {
	case "bool":
		return "boolean", nil
	case "int8", "uint8", "int16", "uint16", "int32", "uint32", "float32", "float64":
		return "number", nil
	case "int64", "uint64", "int128", "uint128", "int256", "uint256", "timestamp", "duration":
		return "bigint", nil
	case "string":
		return "string", nil
	case "uuid":
		return "UUID", nil
	case "bytes":
		return "Uint8Array", nil
	case "arrayString":
		return "string[]", nil
	default:
		return "", fmt.Errorf("unsupported column type %q", kind)
	}
}

func uniqueTypeScriptIdentifiers(names []string, style func(string) string) []namedTypeScriptIdentifier {
	out := make([]namedTypeScriptIdentifier, len(names))
	seen := make(map[string]int, len(names))
	for i, name := range names {
		base := style(name)
		if base == "" {
			base = "_"
		}
		identifier := uniqueTypeScriptIdentifier(base, seen)
		out[i] = namedTypeScriptIdentifier{name: name, identifier: identifier}
	}
	return out
}

func uniqueTypeScriptIdentifier(base string, seen map[string]int) string {
	identifier := base
	if count := seen[identifier]; count > 0 {
		for suffix := count + 1; ; suffix++ {
			candidate := fmt.Sprintf("%s%d", base, suffix)
			if seen[candidate] == 0 {
				identifier = candidate
				break
			}
		}
	}
	seen[identifier]++
	return identifier
}

func typeScriptCamelIdentifier(name string) string {
	words, hadSeparator := identifierWords(name)
	if len(words) == 0 {
		return "_"
	}
	var b strings.Builder
	for i, word := range words {
		normalized := normalizeIdentifierWord(word)
		if i == 0 {
			if hadSeparator {
				normalized = lowerFirst(normalized)
			}
			b.WriteString(normalized)
			continue
		}
		b.WriteString(upperFirst(normalized))
	}
	return ensureTypeScriptIdentifier(b.String())
}

func typeScriptPascalIdentifier(name string) string {
	words, _ := identifierWords(name)
	if len(words) == 0 {
		return "_"
	}
	var b strings.Builder
	for _, word := range words {
		b.WriteString(upperFirst(normalizeIdentifierWord(word)))
	}
	return ensureTypeScriptIdentifier(b.String())
}

func typeScriptLifecycleIdentifier(name string) string {
	return ensureTypeScriptIdentifier(typeScriptPascalIdentifier(name))
}

func identifierWords(name string) ([]string, bool) {
	var words []string
	var b strings.Builder
	hadSeparator := false
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
			continue
		}
		hadSeparator = true
		if b.Len() > 0 {
			words = append(words, b.String())
			b.Reset()
		}
	}
	if b.Len() > 0 {
		words = append(words, b.String())
	}
	return words, hadSeparator
}

func normalizeIdentifierWord(word string) string {
	if word == "" {
		return ""
	}
	if isAllUpperOrDigit(word) || isAllLowerOrDigit(word) {
		return strings.ToLower(word)
	}
	return word
}

func ensureTypeScriptIdentifier(identifier string) string {
	if identifier == "" {
		return "_"
	}
	var b strings.Builder
	for i, r := range identifier {
		if i == 0 && unicode.IsDigit(r) {
			b.WriteRune('_')
			b.WriteRune(r)
			continue
		}
		valid := r == '_' || r == '$' || unicode.IsLetter(r) || unicode.IsDigit(r)
		if !valid {
			b.WriteRune('_')
			continue
		}
		b.WriteRune(r)
	}
	out := b.String()
	if out == "" {
		return "_"
	}
	if typeScriptReservedWords[out] {
		return out + "_"
	}
	return out
}

func upperFirst(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func isAllUpperOrDigit(s string) bool {
	hasLetter := false
	for _, r := range s {
		if !unicode.IsLetter(r) {
			continue
		}
		hasLetter = true
		if unicode.IsLower(r) {
			return false
		}
	}
	return hasLetter
}

func isAllLowerOrDigit(s string) bool {
	hasLetter := false
	for _, r := range s {
		if !unicode.IsLetter(r) {
			continue
		}
		hasLetter = true
		if unicode.IsUpper(r) {
			return false
		}
	}
	return hasLetter
}

var typeScriptReservedWords = map[string]bool{
	"break":      true,
	"case":       true,
	"catch":      true,
	"class":      true,
	"const":      true,
	"continue":   true,
	"debugger":   true,
	"default":    true,
	"delete":     true,
	"do":         true,
	"else":       true,
	"enum":       true,
	"export":     true,
	"extends":    true,
	"false":      true,
	"finally":    true,
	"for":        true,
	"function":   true,
	"if":         true,
	"import":     true,
	"in":         true,
	"instanceof": true,
	"new":        true,
	"null":       true,
	"return":     true,
	"super":      true,
	"switch":     true,
	"this":       true,
	"throw":      true,
	"true":       true,
	"try":        true,
	"typeof":     true,
	"var":        true,
	"void":       true,
	"while":      true,
	"with":       true,
}
