// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.
// Source contract: shunter.module_contract v1
// Module: type_index_canary v0.0.0-test

import type {
  BsatnColumn as ShunterBsatnColumn,
  DecodedDeclaredQueryResult as ShunterDecodedDeclaredQueryResult,
  DeclaredQueryDecodeOptions as ShunterDeclaredQueryDecodeOptions,
  DeclaredQueryOptions as ShunterDeclaredQueryOptions,
  DeclaredQueryRunner as ShunterDeclaredQueryRunner,
  DeclaredViewHandleSubscriber as ShunterDeclaredViewHandleSubscriber,
  DeclaredViewSubscriber as ShunterDeclaredViewSubscriber,
  DeclaredViewSubscriptionOptions as ShunterDeclaredViewSubscriptionOptions,
  EncodedReducerCallOptions as ShunterEncodedReducerCallOptions,
  EncodedReducerCallResultOptions as ShunterEncodedReducerCallResultOptions,
  GeneratedContractMetadata as ShunterGeneratedContractMetadata,
  ProtocolMetadata as ShunterProtocolMetadata,
  ProcedureCaller as ShunterProcedureCaller,
  QueryRunner as ShunterQueryRunner,
  RawDeclaredQueryResult as ShunterRawDeclaredQueryResult,
  ReducerCaller as ShunterReducerCaller,
  ReducerCallResult as ShunterReducerCallResult,
  ReducerCallResultRequestOptions as ShunterReducerCallResultRequestOptions,
  SubscriptionUnsubscribe as ShunterSubscriptionUnsubscribe,
  SubscriptionHandle as ShunterSubscriptionHandle,
  SubscriptionHandleReturnOptions as ShunterSubscriptionHandleReturnOptions,
  SubscriptionRowEvent as ShunterSubscriptionRowEvent,
  TableRowDecoder as ShunterTableRowDecoder,
  TableRowDecoders as ShunterTableRowDecoders,
  TableSubscriber as ShunterTableSubscriber,
  TableSubscriptionOptions as ShunterTableSubscriptionOptions,
  ViewSubscriber as ShunterViewSubscriber,
} from "../../src/index.js";

import {
  decodeBsatnProduct as shunterDecodeBsatnProduct,
} from "../../src/index.js";

export const shunterProtocol = {
  minSupportedVersion: 1,
  currentVersion: 2,
  defaultSubprotocol: "v2.bsatn.shunter",
  supportedSubprotocols: ["v2.bsatn.shunter", "v1.bsatn.shunter"],
} as const satisfies ShunterProtocolMetadata;

export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];

export const shunterContract = {
  contractFormat: "shunter.module_contract",
  contractVersion: 1,
  moduleName: "type_index_canary",
  moduleVersion: "v0.0.0-test",
  generationProfile: "internal",
  runtimeImport: "../../src/index.js",
  protocol: shunterProtocol,
} as const satisfies ShunterGeneratedContractMetadata<typeof shunterProtocol>;

export type ReducerCaller = ShunterReducerCaller<ReducerName, Uint8Array, Uint8Array>;
export type ProcedureCaller = ShunterProcedureCaller<ProcedureName, Uint8Array, Uint8Array>;
export type EncodedReducerCallOptions<Args = unknown> = ShunterEncodedReducerCallOptions<Args>;
export type EncodedReducerCallResultOptions<Args = unknown, Result = Uint8Array> = ShunterEncodedReducerCallResultOptions<Args, Result>;
export type ReducerCallResult<Name extends ReducerName = ReducerName, Result = Uint8Array> = ShunterReducerCallResult<Name, Result>;
export type ReducerCallResultOptions = ShunterReducerCallResultRequestOptions<Uint8Array>;
export type QueryRunner = ShunterQueryRunner<Uint8Array>;
export type ViewSubscriber = ShunterViewSubscriber;
export type DeclaredQueryRunner = ShunterDeclaredQueryRunner<ExecutableQueryName, Uint8Array>;
export type DeclaredQueryOptions = ShunterDeclaredQueryOptions;
export type DeclaredQueryRunOptions = Omit<DeclaredQueryOptions, "params">;
export type RawDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName> = ShunterRawDeclaredQueryResult<Name>;
export type DeclaredQueryDecodeOptions<RowsByName extends object = TableRows> = ShunterDeclaredQueryDecodeOptions<RowsByName>;
export type DeclaredQueryDecodedRunOptions<RowsByName extends object = TableRows> = DeclaredQueryRunOptions & DeclaredQueryDecodeOptions<RowsByName>;
export type DecodedDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName, RowsByName extends object = TableRows> = ShunterDecodedDeclaredQueryResult<Name, RowsByName>;
export type DeclaredViewSubscriber = ShunterDeclaredViewSubscriber<ExecutableViewName>;
export type DeclaredViewHandleSubscriber = ShunterDeclaredViewHandleSubscriber<ExecutableViewName>;
export type DeclaredViewSubscriptionOptions<Row = unknown> = Omit<ShunterDeclaredViewSubscriptionOptions<Row>, "params">;
export type DeclaredViewSubscribeOptions<Row = unknown> = Omit<DeclaredViewSubscriptionOptions<Row>, "returnHandle"> & { readonly returnHandle?: false | undefined };
export type SubscriptionUnsubscribe = ShunterSubscriptionUnsubscribe;
export type SubscriptionHandle<Row = unknown> = ShunterSubscriptionHandle<Row>;
export type SubscriptionHandleReturnOptions = ShunterSubscriptionHandleReturnOptions;
export type SubscriptionRowEvent<Row = unknown> = ShunterSubscriptionRowEvent<Row>;
export type TableRow<Name extends TableName> = TableRows[Name];
export type TableSubscriber<Row = never> = ShunterTableSubscriber<TableName, TableRows, Row>;
export type TableSubscriptionOptions<Row = unknown> = ShunterTableSubscriptionOptions<Row>;
export type TableSubscribeOptions<Row = unknown> = Omit<TableSubscriptionOptions<Row>, "returnHandle"> & { readonly returnHandle?: false | undefined };
export type TableSubscribeCaller<Row = never> = <Table extends TableName>(table: Table, onRows?: (rows: ([Row] extends [never] ? TableRows[Table] : Row)[]) => void, options?: TableSubscribeOptions<[Row] extends [never] ? TableRows[Table] : Row>) => Promise<SubscriptionUnsubscribe>;
export type TableRowDecoder<Name extends TableName> = ShunterTableRowDecoder<TableRows[Name]>;
export type TableRowDecoders<RowsByName extends object = TableRows> = ShunterTableRowDecoders<RowsByName>;
export type UUID = string;

export interface FlatValuesRow {
  id: bigint;
  label: string;
  bucket: string;
  seq: bigint;
  flag: boolean;
  i8: number;
  u8: number;
  i16: number;
  u16: number;
  i32: number;
  u32: number;
  i64: bigint;
  u64: bigint;
  i128: bigint;
  u128: bigint;
  i256: bigint;
  u256: bigint;
  f32: number;
  f64: number;
  createdAt: bigint;
  ttl: bigint;
  uuid: UUID;
  blob: Uint8Array;
  metadata: unknown;
  tags: string[];
  optionalNote: string | null;
}

export const tables = {
  flatValues: "flat_values",
} as const;

export type TableName = (typeof tables)[keyof typeof tables];

export type TableRows = {
  "flat_values": FlatValuesRow;
};

const flatValuesColumns = [
  { name: "id", kind: "uint64" },
  { name: "label", kind: "string" },
  { name: "bucket", kind: "string" },
  { name: "seq", kind: "uint64" },
  { name: "flag", kind: "bool" },
  { name: "i8", kind: "int8" },
  { name: "u8", kind: "uint8" },
  { name: "i16", kind: "int16" },
  { name: "u16", kind: "uint16" },
  { name: "i32", kind: "int32" },
  { name: "u32", kind: "uint32" },
  { name: "i64", kind: "int64" },
  { name: "u64", kind: "uint64" },
  { name: "i128", kind: "int128" },
  { name: "u128", kind: "uint128" },
  { name: "i256", kind: "int256" },
  { name: "u256", kind: "uint256" },
  { name: "f32", kind: "float32" },
  { name: "f64", kind: "float64" },
  { name: "created_at", kind: "timestamp" },
  { name: "ttl", kind: "duration" },
  { name: "uuid", kind: "uuid" },
  { name: "blob", kind: "bytes" },
  { name: "metadata", kind: "json" },
  { name: "tags", kind: "arrayString" },
  { name: "optional_note", kind: "string", nullable: true },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeFlatValuesRow(row: Uint8Array): FlatValuesRow {
  return shunterDecodeBsatnProduct(row, flatValuesColumns, (values) => ({
    id: values[0] as bigint,
    label: values[1] as string,
    bucket: values[2] as string,
    seq: values[3] as bigint,
    flag: values[4] as boolean,
    i8: values[5] as number,
    u8: values[6] as number,
    i16: values[7] as number,
    u16: values[8] as number,
    i32: values[9] as number,
    u32: values[10] as number,
    i64: values[11] as bigint,
    u64: values[12] as bigint,
    i128: values[13] as bigint,
    u128: values[14] as bigint,
    i256: values[15] as bigint,
    u256: values[16] as bigint,
    f32: values[17] as number,
    f64: values[18] as number,
    createdAt: values[19] as bigint,
    ttl: values[20] as bigint,
    uuid: values[21] as UUID,
    blob: values[22] as Uint8Array,
    metadata: values[23] as unknown,
    tags: values[24] as string[],
    optionalNote: values[25] as string | null,
  }));
}

export const tableRowDecoders = {
  "flat_values": decodeFlatValuesRow,
} as const satisfies TableRowDecoders;

export const tableReadPolicies = {
  flatValues: { access: "public", permissions: [] },
} as const;

export const tableKinds = {
  flatValues: "persistent",
} as const;

export const visibilityFilters = {
} as const;

export function subscribeFlatValues(subscribeTable: TableSubscribeCaller<FlatValuesRow>, onRows?: (rows: FlatValuesRow[]) => void, options: TableSubscribeOptions<FlatValuesRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscribeOptions<FlatValuesRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["flat_values"] } : { ...options };
  return subscribeTable("flat_values", onRows, subscribeOptions);
}

export const reducers = {
} as const;

export type ReducerName = (typeof reducers)[keyof typeof reducers];

export const lifecycleReducers = {
} as const;

export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];

export const procedures = {
} as const;

export type ProcedureName = (typeof procedures)[keyof typeof procedures];

export const queries = {
} as const;

export type QueryName = (typeof queries)[keyof typeof queries];

export const querySQL = {
} as const;

export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];

export const views = {
} as const;

export type ViewName = (typeof views)[keyof typeof views];

export const viewSQL = {
} as const;

export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];

export const permissions = {
  reducers: {
  },
  queries: {
  },
  views: {
  },
} as const;

export const readModels = {
  queries: {
  },
  views: {
  },
} as const;

export interface ModuleClientBindings {
  readonly callReducer: ReducerCaller;
  readonly callProcedure: ProcedureCaller;
  readonly runDeclaredQuery: DeclaredQueryRunner;
  readonly subscribeDeclaredView: DeclaredViewSubscriber & DeclaredViewHandleSubscriber;
  readonly subscribeTable: TableSubscribeCaller & (<Table extends string, Row = Table extends TableName ? TableRows[Table] : Uint8Array>(table: Table, onRows?: (rows: Row[]) => void, options?: TableSubscriptionOptions<Row>) => Promise<SubscriptionUnsubscribe | SubscriptionHandle<Row>>);
}

export function createModuleClient(bindings: ModuleClientBindings) {
  return {
    reducers: {
    },
    procedures: {
    },
    queries: {
    },
    views: {
    },
    tables: {
      flatValues: {
        subscribe: (onRows?: (rows: FlatValuesRow[]) => void, options: TableSubscribeOptions<FlatValuesRow> = {}) => subscribeFlatValues(bindings.subscribeTable, onRows, options),
      },
    },
    events: {
    },
  } as const;
}

