// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.
// Source contract: shunter.module_contract v1
// Module: public_profile v0.1.0

import type {
  BsatnColumn as ShunterBsatnColumn,
  DecodedDeclaredQueryResult as ShunterDecodedDeclaredQueryResult,
  DeclaredQueryDecodeOptions as ShunterDeclaredQueryDecodeOptions,
  DeclaredQueryOptions as ShunterDeclaredQueryOptions,
  DeclaredQueryRunner as ShunterDeclaredQueryRunner,
  DeclaredViewHandleSubscriber as ShunterDeclaredViewHandleSubscriber,
  DeclaredViewSubscriber as ShunterDeclaredViewSubscriber,
  DeclaredViewSubscriptionOptions as ShunterDeclaredViewSubscriptionOptions,
  EncodedReducerCallOptions as ShunterEncodedReducerCallOptions,
  EncodedReducerCallResultOptions as ShunterEncodedReducerCallResultOptions,
  GeneratedContractMetadata as ShunterGeneratedContractMetadata,
  ProtocolMetadata as ShunterProtocolMetadata,
  ProcedureCaller as ShunterProcedureCaller,
  QueryRunner as ShunterQueryRunner,
  RawDeclaredQueryResult as ShunterRawDeclaredQueryResult,
  ReducerCaller as ShunterReducerCaller,
  ReducerCallResult as ShunterReducerCallResult,
  ReducerCallResultRequestOptions as ShunterReducerCallResultRequestOptions,
  SubscriptionUnsubscribe as ShunterSubscriptionUnsubscribe,
  SubscriptionHandle as ShunterSubscriptionHandle,
  SubscriptionHandleReturnOptions as ShunterSubscriptionHandleReturnOptions,
  SubscriptionRowEvent as ShunterSubscriptionRowEvent,
  TableRowDecoder as ShunterTableRowDecoder,
  TableRowDecoders as ShunterTableRowDecoders,
  TableSubscriber as ShunterTableSubscriber,
  TableSubscriptionOptions as ShunterTableSubscriptionOptions,
  ViewSubscriber as ShunterViewSubscriber,
} from "@shunter/client";

import {
  decodeBsatnProduct as shunterDecodeBsatnProduct,
  decodeDeclaredQueryResult as shunterDecodeDeclaredQueryResult,
} from "@shunter/client";

export const shunterProtocol = {
  minSupportedVersion: 1,
  currentVersion: 2,
  defaultSubprotocol: "v2.bsatn.shunter",
  supportedSubprotocols: ["v2.bsatn.shunter", "v1.bsatn.shunter"],
} as const satisfies ShunterProtocolMetadata;

export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];

export const shunterContract = {
  contractFormat: "shunter.module_contract",
  contractVersion: 1,
  moduleName: "public_profile",
  moduleVersion: "v0.1.0",
  generationProfile: "public",
  runtimeImport: "@shunter/client",
  protocol: shunterProtocol,
} as const satisfies ShunterGeneratedContractMetadata<typeof shunterProtocol>;

export type ReducerCaller = ShunterReducerCaller<ReducerName, Uint8Array, Uint8Array>;
export type ProcedureCaller = ShunterProcedureCaller<ProcedureName, Uint8Array, Uint8Array>;
export type EncodedReducerCallOptions<Args = unknown> = ShunterEncodedReducerCallOptions<Args>;
export type EncodedReducerCallResultOptions<Args = unknown, Result = Uint8Array> = ShunterEncodedReducerCallResultOptions<Args, Result>;
export type ReducerCallResult<Name extends ReducerName = ReducerName, Result = Uint8Array> = ShunterReducerCallResult<Name, Result>;
export type ReducerCallResultOptions = ShunterReducerCallResultRequestOptions<Uint8Array>;
export type QueryRunner = ShunterQueryRunner<Uint8Array>;
export type ViewSubscriber = ShunterViewSubscriber;
export type DeclaredQueryRunner = ShunterDeclaredQueryRunner<ExecutableQueryName, Uint8Array>;
export type DeclaredQueryOptions = ShunterDeclaredQueryOptions;
export type DeclaredQueryRunOptions = Omit<DeclaredQueryOptions, "params">;
export type RawDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName> = ShunterRawDeclaredQueryResult<Name>;
export type DeclaredQueryDecodeOptions<RowsByName extends object = TableRows> = ShunterDeclaredQueryDecodeOptions<RowsByName>;
export type DeclaredQueryDecodedRunOptions<RowsByName extends object = TableRows> = DeclaredQueryRunOptions & DeclaredQueryDecodeOptions<RowsByName>;
export type DecodedDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName, RowsByName extends object = TableRows> = ShunterDecodedDeclaredQueryResult<Name, RowsByName>;
export type DeclaredViewSubscriber = ShunterDeclaredViewSubscriber<ExecutableViewName>;
export type DeclaredViewHandleSubscriber = ShunterDeclaredViewHandleSubscriber<ExecutableViewName>;
export type DeclaredViewSubscriptionOptions<Row = unknown> = Omit<ShunterDeclaredViewSubscriptionOptions<Row>, "params">;
export type DeclaredViewSubscribeOptions<Row = unknown> = Omit<DeclaredViewSubscriptionOptions<Row>, "returnHandle"> & { readonly returnHandle?: false | undefined };
export type SubscriptionUnsubscribe = ShunterSubscriptionUnsubscribe;
export type SubscriptionHandle<Row = unknown> = ShunterSubscriptionHandle<Row>;
export type SubscriptionHandleReturnOptions = ShunterSubscriptionHandleReturnOptions;
export type SubscriptionRowEvent<Row = unknown> = ShunterSubscriptionRowEvent<Row>;
export type TableRow<Name extends TableName> = TableRows[Name];
export type TableSubscriber<Row = never> = ShunterTableSubscriber<TableName, TableRows, Row>;
export type TableSubscriptionOptions<Row = unknown> = ShunterTableSubscriptionOptions<Row>;
export type TableSubscribeOptions<Row = unknown> = Omit<TableSubscriptionOptions<Row>, "returnHandle"> & { readonly returnHandle?: false | undefined };
export type TableSubscribeCaller<Row = never> = <Table extends TableName>(table: Table, onRows?: (rows: ([Row] extends [never] ? TableRows[Table] : Row)[]) => void, options?: TableSubscribeOptions<[Row] extends [never] ? TableRows[Table] : Row>) => Promise<SubscriptionUnsubscribe>;
export type TableRowDecoder<Name extends TableName> = ShunterTableRowDecoder<TableRows[Name]>;
export type TableRowDecoders<RowsByName extends object = TableRows> = ShunterTableRowDecoders<RowsByName>;
export type UUID = string;

export interface MessagesRow {
  id: bigint;
  body: string;
}

export interface SysVisibleRow {
  id: bigint;
}

export interface NotificationsRow {
  id: bigint;
  message: string;
}

export const tables = {
  messages: "messages",
  sysVisible: "sys_visible",
  notifications: "notifications",
} as const;

export type TableName = (typeof tables)[keyof typeof tables];

export type TableRows = {
  "messages": MessagesRow;
  "sys_visible": SysVisibleRow;
  "notifications": NotificationsRow;
};

const messagesColumns = [
  { name: "id", kind: "uint64" },
  { name: "body", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeMessagesRow(row: Uint8Array): MessagesRow {
  return shunterDecodeBsatnProduct(row, messagesColumns, (values) => ({
    id: values[0] as bigint,
    body: values[1] as string,
  }));
}

const sysVisibleColumns = [
  { name: "id", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeSysVisibleRow(row: Uint8Array): SysVisibleRow {
  return shunterDecodeBsatnProduct(row, sysVisibleColumns, (values) => ({
    id: values[0] as bigint,
  }));
}

const notificationsColumns = [
  { name: "id", kind: "uint64" },
  { name: "message", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeNotificationsRow(row: Uint8Array): NotificationsRow {
  return shunterDecodeBsatnProduct(row, notificationsColumns, (values) => ({
    id: values[0] as bigint,
    message: values[1] as string,
  }));
}

export const tableRowDecoders = {
  "messages": decodeMessagesRow,
  "sys_visible": decodeSysVisibleRow,
  "notifications": decodeNotificationsRow,
} as const satisfies TableRowDecoders;

export const tableReadPolicies = {
  messages: { access: "private", permissions: [] },
  sysVisible: { access: "private", permissions: [] },
  notifications: { access: "private", permissions: [] },
} as const;

export const tableKinds = {
  messages: "persistent",
  sysVisible: "persistent",
  notifications: "event",
} as const;

export const visibilityFilters = {
} as const;

export function subscribeMessages(subscribeTable: TableSubscribeCaller<MessagesRow>, onRows?: (rows: MessagesRow[]) => void, options: TableSubscribeOptions<MessagesRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscribeOptions<MessagesRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["messages"] } : { ...options };
  return subscribeTable("messages", onRows, subscribeOptions);
}

export function subscribeSysVisible(subscribeTable: TableSubscribeCaller<SysVisibleRow>, onRows?: (rows: SysVisibleRow[]) => void, options: TableSubscribeOptions<SysVisibleRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscribeOptions<SysVisibleRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["sys_visible"] } : { ...options };
  return subscribeTable("sys_visible", onRows, subscribeOptions);
}

export function subscribeNotifications(subscribeTable: TableSubscribeCaller<NotificationsRow>, onRows?: (rows: NotificationsRow[]) => void, options: TableSubscribeOptions<NotificationsRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscribeOptions<NotificationsRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["notifications"], eventTable: true } : { ...options, eventTable: true };
  return subscribeTable("notifications", onRows, subscribeOptions);
}

export function subscribeNotificationsInserts(subscribeTable: TableSubscribeCaller<NotificationsRow>, onInsert: (event: SubscriptionRowEvent<NotificationsRow>) => void, options: TableSubscribeOptions<NotificationsRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscribeOptions<NotificationsRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["notifications"], eventTable: true, onInsert } : { ...options, eventTable: true, onInsert };
  return subscribeTable("notifications", undefined, subscribeOptions);
}

export const reducers = {
} as const;

export type ReducerName = (typeof reducers)[keyof typeof reducers];

export const lifecycleReducers = {
} as const;

export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];

export const procedures = {
} as const;

export type ProcedureName = (typeof procedures)[keyof typeof procedures];

export const queries = {
  privateNoteSummaries: "private_note_summaries",
} as const;

export type QueryName = (typeof queries)[keyof typeof queries];

export const querySQL = {
  privateNoteSummaries: "SELECT id, body FROM private_notes",
} as const;

export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];

export interface PrivateNoteSummariesQueryRow {
  id: bigint;
  body: string;
}

const privateNoteSummariesQueryColumns = [
  { name: "id", kind: "uint64" },
  { name: "body", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodePrivateNoteSummariesQueryRow(row: Uint8Array): PrivateNoteSummariesQueryRow {
  return shunterDecodeBsatnProduct(row, privateNoteSummariesQueryColumns, (values) => ({
    id: values[0] as bigint,
    body: values[1] as string,
  }));
}

export type PrivateNoteSummariesQueryRows = {
  "private_notes": PrivateNoteSummariesQueryRow;
};

export const privateNoteSummariesQueryRowDecoders = {
  "private_notes": decodePrivateNoteSummariesQueryRow,
} as const satisfies TableRowDecoders<PrivateNoteSummariesQueryRows>;

export function queryPrivateNoteSummaries(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("private_note_summaries");
}

export function queryPrivateNoteSummariesResult(data: unknown, options: DeclaredQueryDecodeOptions<PrivateNoteSummariesQueryRows> = {}): DecodedDeclaredQueryResult<typeof queries.privateNoteSummaries, PrivateNoteSummariesQueryRows> {
  const decodeOptions: DeclaredQueryDecodeOptions<PrivateNoteSummariesQueryRows> = options.tableDecoders === undefined && options.decodeRow === undefined ? { ...options, tableDecoders: privateNoteSummariesQueryRowDecoders } : options;
  return shunterDecodeDeclaredQueryResult("private_note_summaries", data, decodeOptions);
}

export async function queryPrivateNoteSummariesDecoded(runDeclaredQuery: DeclaredQueryRunner, options: DeclaredQueryDecodeOptions<PrivateNoteSummariesQueryRows> = {}): Promise<DecodedDeclaredQueryResult<typeof queries.privateNoteSummaries, PrivateNoteSummariesQueryRows>> {
  return queryPrivateNoteSummariesResult(await runDeclaredQuery("private_note_summaries"), options);
}

export const views = {
  liveInternalAudit: "live_internal_audit",
} as const;

export type ViewName = (typeof views)[keyof typeof views];

export const viewSQL = {
  liveInternalAudit: "SELECT id, action FROM internal_notes",
} as const;

export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];

export interface LiveInternalAuditViewRow {
  id: bigint;
  action: string;
}

const liveInternalAuditViewColumns = [
  { name: "id", kind: "uint64" },
  { name: "action", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeLiveInternalAuditViewRow(row: Uint8Array): LiveInternalAuditViewRow {
  return shunterDecodeBsatnProduct(row, liveInternalAuditViewColumns, (values) => ({
    id: values[0] as bigint,
    action: values[1] as string,
  }));
}

export function subscribeLiveInternalAudit(subscribeDeclaredView: DeclaredViewSubscriber, options: DeclaredViewSubscribeOptions<LiveInternalAuditViewRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: DeclaredViewSubscribeOptions<LiveInternalAuditViewRow> = options.decodeRow === undefined ? { ...options, decodeRow: decodeLiveInternalAuditViewRow } : options;
  return subscribeDeclaredView("live_internal_audit", subscribeOptions);
}

export function subscribeLiveInternalAuditHandle(subscribeDeclaredView: DeclaredViewHandleSubscriber, options: DeclaredViewSubscriptionOptions<LiveInternalAuditViewRow> & SubscriptionHandleReturnOptions): Promise<SubscriptionHandle<LiveInternalAuditViewRow>> {
  const subscribeOptions: DeclaredViewSubscriptionOptions<LiveInternalAuditViewRow> & SubscriptionHandleReturnOptions = options.decodeRow === undefined ? { ...options, decodeRow: decodeLiveInternalAuditViewRow } : options;
  return subscribeDeclaredView("live_internal_audit", subscribeOptions);
}

export const permissions = {
  reducers: {
  },
  queries: {
    privateNoteSummaries: { required: ["notes:read"] },
  },
  views: {
    liveInternalAudit: { required: ["audit:read"] },
  },
} as const;

export const readModels = {
  queries: {
    privateNoteSummaries: { tables: ["private_notes"], tags: ["public-query"] },
  },
  views: {
    liveInternalAudit: { tables: ["internal_notes"], tags: ["internal-view"] },
  },
} as const;

export interface ModuleClientBindings {
  readonly callReducer: ReducerCaller;
  readonly callProcedure: ProcedureCaller;
  readonly runDeclaredQuery: DeclaredQueryRunner;
  readonly subscribeDeclaredView: DeclaredViewSubscriber & DeclaredViewHandleSubscriber;
  readonly subscribeTable: TableSubscribeCaller & (<Table extends string, Row = Table extends TableName ? TableRows[Table] : Uint8Array>(table: Table, onRows?: (rows: Row[]) => void, options?: TableSubscriptionOptions<Row>) => Promise<SubscriptionUnsubscribe | SubscriptionHandle<Row>>);
}

export function createModuleClient(bindings: ModuleClientBindings) {
  return {
    reducers: {
    },
    procedures: {
    },
    queries: {
      privateNoteSummaries: {
        run: (options: DeclaredQueryRunOptions = {}) => bindings.runDeclaredQuery("private_note_summaries", options),
        decoded: (options: DeclaredQueryDecodeOptions<PrivateNoteSummariesQueryRows> = {}) => queryPrivateNoteSummariesDecoded(bindings.runDeclaredQuery, options),
      },
    },
    views: {
      liveInternalAudit: {
        subscribe: (options: DeclaredViewSubscribeOptions<LiveInternalAuditViewRow> = {}) => subscribeLiveInternalAudit(bindings.subscribeDeclaredView, options),
        handle: (options: DeclaredViewSubscriptionOptions<LiveInternalAuditViewRow> & SubscriptionHandleReturnOptions) => subscribeLiveInternalAuditHandle(bindings.subscribeDeclaredView, options),
      },
    },
    tables: {
      messages: {
        subscribe: (onRows?: (rows: MessagesRow[]) => void, options: TableSubscribeOptions<MessagesRow> = {}) => subscribeMessages(bindings.subscribeTable, onRows, options),
      },
      sysVisible: {
        subscribe: (onRows?: (rows: SysVisibleRow[]) => void, options: TableSubscribeOptions<SysVisibleRow> = {}) => subscribeSysVisible(bindings.subscribeTable, onRows, options),
      },
      notifications: {
        subscribe: (onRows?: (rows: NotificationsRow[]) => void, options: TableSubscribeOptions<NotificationsRow> = {}) => subscribeNotifications(bindings.subscribeTable, onRows, options),
      },
    },
    events: {
      notifications: {
        onInsert: (handler: (event: SubscriptionRowEvent<NotificationsRow>) => void, options: TableSubscribeOptions<NotificationsRow> = {}) => subscribeNotificationsInserts(bindings.subscribeTable, handler, options),
      },
    },
  } as const;
}

