// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.
// Source contract: shunter.module_contract v1
// Module: chat v1.2.3

import type {
  DeclaredQueryRunner as ShunterDeclaredQueryRunner,
  DeclaredViewSubscriber as ShunterDeclaredViewSubscriber,
  ProtocolMetadata as ShunterProtocolMetadata,
  QueryRunner as ShunterQueryRunner,
  RawDeclaredQueryResult as ShunterRawDeclaredQueryResult,
  ReducerCaller as ShunterReducerCaller,
  ReducerCallResult as ShunterReducerCallResult,
  SubscriptionUnsubscribe as ShunterSubscriptionUnsubscribe,
  TableSubscriber as ShunterTableSubscriber,
  ViewSubscriber as ShunterViewSubscriber,
} from "@shunter/client";

export const shunterProtocol = {
  minSupportedVersion: 1,
  currentVersion: 1,
  defaultSubprotocol: "v1.bsatn.shunter",
  supportedSubprotocols: ["v1.bsatn.shunter"],
} as const satisfies ShunterProtocolMetadata;

export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];

export type ReducerCaller = ShunterReducerCaller<ReducerName, Uint8Array, Uint8Array>;
export type ReducerCallResult<Name extends ReducerName = ReducerName> = ShunterReducerCallResult<Name, Uint8Array>;
export type QueryRunner = ShunterQueryRunner<Uint8Array>;
export type ViewSubscriber = ShunterViewSubscriber;
export type DeclaredQueryRunner = ShunterDeclaredQueryRunner<ExecutableQueryName, Uint8Array>;
export type RawDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName> = ShunterRawDeclaredQueryResult<Name>;
export type DeclaredViewSubscriber = ShunterDeclaredViewSubscriber<ExecutableViewName>;
export type SubscriptionUnsubscribe = ShunterSubscriptionUnsubscribe;
export type TableRow<Name extends TableName> = TableRows[Name];
export type TableSubscriber<Row = never> = ShunterTableSubscriber<TableName, TableRows, Row>;
export type UUID = string;

export interface MessagesRow {
  id: bigint;
  body: string;
  sentAt: bigint;
  payload: Uint8Array;
  tags: string[];
}

export interface _Row {
  id: bigint;
}

export interface _1TableRow {
  id: bigint;
}

export interface ClassRow {
  bodyText: string;
  bodyText2: string;
  class_: bigint;
  _1Count: bigint;
}

export interface Class2Row {
  id: bigint;
}

export const tables = {
  messages: "messages",
  _: "!!!",
  _1Table: "1-table",
  class_: "class",
  class_2: "class!",
} as const;

export type TableName = (typeof tables)[keyof typeof tables];

export type TableRows = {
  "messages": MessagesRow;
  "!!!": _Row;
  "1-table": _1TableRow;
  "class": ClassRow;
  "class!": Class2Row;
};

export const tableReadPolicies = {
  messages: { access: "private", permissions: [] },
  _: { access: "private", permissions: [] },
  _1Table: { access: "private", permissions: [] },
  class_: { access: "private", permissions: [] },
  class_2: { access: "private", permissions: [] },
} as const;

export const visibilityFilters = {
  ownMessages: { sql: "SELECT * FROM messages WHERE body = 'own'", returnTable: "messages", returnTableId: 0, usesCallerIdentity: false },
  ownMessages2: { sql: "SELECT * FROM messages WHERE body = 'archived'", returnTable: "messages", returnTableId: 0, usesCallerIdentity: false },
  class_: { sql: "SELECT * FROM messages WHERE body = 'reserved'", returnTable: "messages", returnTableId: 0, usesCallerIdentity: false },
} as const;

export function subscribeMessages(subscribeTable: TableSubscriber<MessagesRow>): Promise<SubscriptionUnsubscribe> {
  return subscribeTable("messages");
}

export function subscribe_(subscribeTable: TableSubscriber<_Row>): Promise<SubscriptionUnsubscribe> {
  return subscribeTable("!!!");
}

export function subscribe_1Table(subscribeTable: TableSubscriber<_1TableRow>): Promise<SubscriptionUnsubscribe> {
  return subscribeTable("1-table");
}

export function subscribeClass(subscribeTable: TableSubscriber<ClassRow>): Promise<SubscriptionUnsubscribe> {
  return subscribeTable("class");
}

export function subscribeClass2(subscribeTable: TableSubscriber<Class2Row>): Promise<SubscriptionUnsubscribe> {
  return subscribeTable("class!");
}

export const reducers = {
  sendMessage: "send_message",
  sendMessage2: "send-message",
  default_: "default",
} as const;

export type ReducerName = (typeof reducers)[keyof typeof reducers];

export function callSendMessage(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("send_message", args);
}

export function callSendMessage2(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("send-message", args);
}

export function callDefault_(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("default", args);
}

export const lifecycleReducers = {
  OnConnect: "OnConnect",
  OnConnect2: "on-connect",
  Default: "default!",
} as const;

export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];

export const queries = {
  recentMessages: "recent_messages",
  recentMessages2: "recent-messages",
  class_: "class",
  sQL: "sQL",
} as const;

export type QueryName = (typeof queries)[keyof typeof queries];

export const querySQL = {
  recentMessages: "SELECT * FROM messages",
  recentMessages2: "SELECT * FROM messages",
  class_: "SELECT * FROM messages",
  sQL: "SELECT * FROM messages",
} as const;

export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];

export function queryRecentMessages(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("recent_messages");
}

export function queryRecentMessages2(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("recent-messages");
}

export function queryClass_(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("class");
}

export function querySQL2(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("sQL");
}

export const views = {
  liveMessages: "live_messages",
  liveMessages2: "live messages",
  default_: "default",
} as const;

export type ViewName = (typeof views)[keyof typeof views];

export const viewSQL = {
  liveMessages: "SELECT * FROM messages",
  liveMessages2: "SELECT * FROM messages",
  default_: "SELECT * FROM messages",
} as const;

export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];

export function subscribeLiveMessages(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {
  return subscribeDeclaredView("live_messages");
}

export function subscribeLiveMessages2(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {
  return subscribeDeclaredView("live messages");
}

export function subscribeDefault_(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {
  return subscribeDeclaredView("default");
}

export const permissions = {
  reducers: {
    sendMessage: { required: ["messages:send"] },
    sendMessage2: { required: ["messages:send-alt"] },
    default_: { required: ["messages:send-default"] },
  },
  queries: {
    recentMessages: { required: ["messages:read"] },
    recentMessages2: { required: ["messages:read-alt"] },
    class_: { required: ["messages:read-class"] },
    sQL: { required: ["messages:read-sql"] },
  },
  views: {
    liveMessages: { required: ["messages:subscribe"] },
    liveMessages2: { required: ["messages:subscribe-alt"] },
    default_: { required: ["messages:subscribe-default"] },
  },
} as const;

export const readModels = {
  queries: {
    recentMessages: { tables: ["messages"], tags: ["history"] },
    recentMessages2: { tables: ["messages"], tags: ["history-alt"] },
    class_: { tables: ["messages"], tags: ["history-class"] },
    sQL: { tables: ["messages"], tags: ["history-sql"] },
  },
  views: {
    liveMessages: { tables: ["messages"], tags: ["realtime"] },
    liveMessages2: { tables: ["messages"], tags: ["realtime-alt"] },
    default_: { tables: ["messages"], tags: ["realtime-default"] },
  },
} as const;

