// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.
// Source contract: shunter.module_contract v1
// Module: chat v1.2.3

import type {
  BsatnColumn as ShunterBsatnColumn,
  DecodedDeclaredQueryResult as ShunterDecodedDeclaredQueryResult,
  DeclaredQueryDecodeOptions as ShunterDeclaredQueryDecodeOptions,
  DeclaredQueryRunner as ShunterDeclaredQueryRunner,
  DeclaredViewHandleSubscriber as ShunterDeclaredViewHandleSubscriber,
  DeclaredViewSubscriber as ShunterDeclaredViewSubscriber,
  DeclaredViewSubscriptionOptions as ShunterDeclaredViewSubscriptionOptions,
  EncodedReducerCallOptions as ShunterEncodedReducerCallOptions,
  EncodedReducerCallResultOptions as ShunterEncodedReducerCallResultOptions,
  GeneratedContractMetadata as ShunterGeneratedContractMetadata,
  ProtocolMetadata as ShunterProtocolMetadata,
  QueryRunner as ShunterQueryRunner,
  RawDeclaredQueryResult as ShunterRawDeclaredQueryResult,
  ReducerCaller as ShunterReducerCaller,
  ReducerCallResult as ShunterReducerCallResult,
  ReducerCallResultRequestOptions as ShunterReducerCallResultRequestOptions,
  SubscriptionUnsubscribe as ShunterSubscriptionUnsubscribe,
  SubscriptionHandle as ShunterSubscriptionHandle,
  SubscriptionHandleReturnOptions as ShunterSubscriptionHandleReturnOptions,
  TableRowDecoder as ShunterTableRowDecoder,
  TableRowDecoders as ShunterTableRowDecoders,
  TableSubscriber as ShunterTableSubscriber,
  TableSubscriptionOptions as ShunterTableSubscriptionOptions,
  ViewSubscriber as ShunterViewSubscriber,
} from "@shunter/client";

import {
  callReducerWithEncodedArgs as shunterCallReducerWithEncodedArgs,
  callReducerWithResult as shunterCallReducerWithResult,
  decodeBsatnProduct as shunterDecodeBsatnProduct,
  decodeDeclaredQueryResult as shunterDecodeDeclaredQueryResult,
  encodeBsatnProduct as shunterEncodeBsatnProduct,
} from "@shunter/client";

export const shunterProtocol = {
  minSupportedVersion: 1,
  currentVersion: 1,
  defaultSubprotocol: "v1.bsatn.shunter",
  supportedSubprotocols: ["v1.bsatn.shunter"],
} as const satisfies ShunterProtocolMetadata;

export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];

export const shunterContract = {
  contractFormat: "shunter.module_contract",
  contractVersion: 1,
  moduleName: "chat",
  moduleVersion: "v1.2.3",
  protocol: shunterProtocol,
} as const satisfies ShunterGeneratedContractMetadata<typeof shunterProtocol>;

export type ReducerCaller = ShunterReducerCaller<ReducerName, Uint8Array, Uint8Array>;
export type EncodedReducerCallOptions<Args = unknown> = ShunterEncodedReducerCallOptions<Args>;
export type EncodedReducerCallResultOptions<Args = unknown, Result = Uint8Array> = ShunterEncodedReducerCallResultOptions<Args, Result>;
export type ReducerCallResult<Name extends ReducerName = ReducerName, Result = Uint8Array> = ShunterReducerCallResult<Name, Result>;
export type ReducerCallResultOptions = ShunterReducerCallResultRequestOptions<Uint8Array>;
export type QueryRunner = ShunterQueryRunner<Uint8Array>;
export type ViewSubscriber = ShunterViewSubscriber;
export type DeclaredQueryRunner = ShunterDeclaredQueryRunner<ExecutableQueryName, Uint8Array>;
export type RawDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName> = ShunterRawDeclaredQueryResult<Name>;
export type DeclaredQueryDecodeOptions<RowsByName extends object = TableRows> = ShunterDeclaredQueryDecodeOptions<RowsByName>;
export type DecodedDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName, RowsByName extends object = TableRows> = ShunterDecodedDeclaredQueryResult<Name, RowsByName>;
export type DeclaredViewSubscriber = ShunterDeclaredViewSubscriber<ExecutableViewName>;
export type DeclaredViewHandleSubscriber = ShunterDeclaredViewHandleSubscriber<ExecutableViewName>;
export type DeclaredViewSubscriptionOptions<Row = unknown> = ShunterDeclaredViewSubscriptionOptions<Row>;
export type SubscriptionUnsubscribe = ShunterSubscriptionUnsubscribe;
export type SubscriptionHandle<Row = unknown> = ShunterSubscriptionHandle<Row>;
export type SubscriptionHandleReturnOptions = ShunterSubscriptionHandleReturnOptions;
export type TableRow<Name extends TableName> = TableRows[Name];
export type TableSubscriber<Row = never> = ShunterTableSubscriber<TableName, TableRows, Row>;
export type TableSubscriptionOptions<Row = unknown> = ShunterTableSubscriptionOptions<Row>;
export type TableRowDecoder<Name extends TableName> = ShunterTableRowDecoder<TableRows[Name]>;
export type TableRowDecoders<RowsByName extends object = TableRows> = ShunterTableRowDecoders<RowsByName>;
export type UUID = string;

export interface MessagesRow {
  id: bigint;
  body: string;
  sentAt: bigint;
  payload: Uint8Array;
  tags: string[];
}

export interface _Row {
  id: bigint;
}

export interface _1TableRow {
  id: bigint;
}

export interface ClassRow {
  bodyText: string;
  bodyText2: string;
  class_: bigint;
  _1Count: bigint;
}

export interface Class2Row {
  id: bigint;
}

export const tables = {
  messages: "messages",
  _: "!!!",
  _1Table: "1-table",
  class_: "class",
  class_2: "class!",
} as const;

export type TableName = (typeof tables)[keyof typeof tables];

export type TableRows = {
  "messages": MessagesRow;
  "!!!": _Row;
  "1-table": _1TableRow;
  "class": ClassRow;
  "class!": Class2Row;
};

const messagesColumns = [
  { name: "id", kind: "uint64" },
  { name: "body", kind: "string" },
  { name: "sent_at", kind: "timestamp" },
  { name: "payload", kind: "bytes" },
  { name: "tags", kind: "arrayString" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeMessagesRow(row: Uint8Array): MessagesRow {
  return shunterDecodeBsatnProduct(row, messagesColumns, (values) => ({
    id: values[0] as bigint,
    body: values[1] as string,
    sentAt: values[2] as bigint,
    payload: values[3] as Uint8Array,
    tags: values[4] as string[],
  }));
}

const _Columns = [
  { name: "id", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decode_Row(row: Uint8Array): _Row {
  return shunterDecodeBsatnProduct(row, _Columns, (values) => ({
    id: values[0] as bigint,
  }));
}

const _1TableColumns = [
  { name: "id", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decode_1TableRow(row: Uint8Array): _1TableRow {
  return shunterDecodeBsatnProduct(row, _1TableColumns, (values) => ({
    id: values[0] as bigint,
  }));
}

const classColumns = [
  { name: "body_text", kind: "string" },
  { name: "body-text", kind: "string" },
  { name: "class", kind: "uint64" },
  { name: "1-count", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeClassRow(row: Uint8Array): ClassRow {
  return shunterDecodeBsatnProduct(row, classColumns, (values) => ({
    bodyText: values[0] as string,
    bodyText2: values[1] as string,
    class_: values[2] as bigint,
    _1Count: values[3] as bigint,
  }));
}

const class2Columns = [
  { name: "id", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeClass2Row(row: Uint8Array): Class2Row {
  return shunterDecodeBsatnProduct(row, class2Columns, (values) => ({
    id: values[0] as bigint,
  }));
}

export const tableRowDecoders = {
  "messages": decodeMessagesRow,
  "!!!": decode_Row,
  "1-table": decode_1TableRow,
  "class": decodeClassRow,
  "class!": decodeClass2Row,
} as const satisfies TableRowDecoders;

export const tableReadPolicies = {
  messages: { access: "private", permissions: [] },
  _: { access: "private", permissions: [] },
  _1Table: { access: "private", permissions: [] },
  class_: { access: "private", permissions: [] },
  class_2: { access: "private", permissions: [] },
} as const;

export const visibilityFilters = {
  ownMessages: { sql: "SELECT * FROM messages WHERE body = 'own'", returnTable: "messages", returnTableId: 0, usesCallerIdentity: false },
  ownMessages2: { sql: "SELECT * FROM messages WHERE body = 'archived'", returnTable: "messages", returnTableId: 0, usesCallerIdentity: false },
  class_: { sql: "SELECT * FROM messages WHERE body = 'reserved'", returnTable: "messages", returnTableId: 0, usesCallerIdentity: false },
} as const;

export function subscribeMessages(subscribeTable: TableSubscriber<MessagesRow>, onRows?: (rows: MessagesRow[]) => void, options: TableSubscriptionOptions<MessagesRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<MessagesRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["messages"] } : options;
  return subscribeTable("messages", onRows, subscribeOptions);
}

export function subscribe_(subscribeTable: TableSubscriber<_Row>, onRows?: (rows: _Row[]) => void, options: TableSubscriptionOptions<_Row> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<_Row> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["!!!"] } : options;
  return subscribeTable("!!!", onRows, subscribeOptions);
}

export function subscribe_1Table(subscribeTable: TableSubscriber<_1TableRow>, onRows?: (rows: _1TableRow[]) => void, options: TableSubscriptionOptions<_1TableRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<_1TableRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["1-table"] } : options;
  return subscribeTable("1-table", onRows, subscribeOptions);
}

export function subscribeClass(subscribeTable: TableSubscriber<ClassRow>, onRows?: (rows: ClassRow[]) => void, options: TableSubscriptionOptions<ClassRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<ClassRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["class"] } : options;
  return subscribeTable("class", onRows, subscribeOptions);
}

export function subscribeClass2(subscribeTable: TableSubscriber<Class2Row>, onRows?: (rows: Class2Row[]) => void, options: TableSubscriptionOptions<Class2Row> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<Class2Row> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["class!"] } : options;
  return subscribeTable("class!", onRows, subscribeOptions);
}

export const reducers = {
  sendMessage: "send_message",
  sendMessage2: "send-message",
  default_: "default",
} as const;

export type ReducerName = (typeof reducers)[keyof typeof reducers];

export function callSendMessage(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("send_message", args);
}

export function callSendMessageResult(callReducer: ReducerCaller, args: Uint8Array, options: ReducerCallResultOptions = {}): Promise<ReducerCallResult<typeof reducers.sendMessage>> {
  return shunterCallReducerWithResult(callReducer, "send_message", args, options);
}

export function callSendMessage2(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("send-message", args);
}

export function callSendMessage2Result(callReducer: ReducerCaller, args: Uint8Array, options: ReducerCallResultOptions = {}): Promise<ReducerCallResult<typeof reducers.sendMessage2>> {
  return shunterCallReducerWithResult(callReducer, "send-message", args, options);
}

export function callDefault_(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("default", args);
}

export function callDefault_Result(callReducer: ReducerCaller, args: Uint8Array, options: ReducerCallResultOptions = {}): Promise<ReducerCallResult<typeof reducers.default_>> {
  return shunterCallReducerWithResult(callReducer, "default", args, options);
}

export const lifecycleReducers = {
  OnConnect: "OnConnect",
  OnConnect2: "on-connect",
  Default: "default!",
} as const;

export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];

export const queries = {
  recentMessages: "recent_messages",
  recentMessages2: "recent-messages",
  class_: "class",
  sQL: "sQL",
} as const;

export type QueryName = (typeof queries)[keyof typeof queries];

export const querySQL = {
  recentMessages: "SELECT * FROM messages",
  recentMessages2: "SELECT * FROM messages",
  class_: "SELECT * FROM messages",
  sQL: "SELECT * FROM messages",
} as const;

export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];

export function queryRecentMessages(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("recent_messages");
}

export function queryRecentMessagesResult<RowsByName extends object = TableRows>(data: unknown, options: DeclaredQueryDecodeOptions<RowsByName>): DecodedDeclaredQueryResult<typeof queries.recentMessages, RowsByName> {
  return shunterDecodeDeclaredQueryResult("recent_messages", data, options);
}

export function queryRecentMessages2(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("recent-messages");
}

export function queryRecentMessages2Result<RowsByName extends object = TableRows>(data: unknown, options: DeclaredQueryDecodeOptions<RowsByName>): DecodedDeclaredQueryResult<typeof queries.recentMessages2, RowsByName> {
  return shunterDecodeDeclaredQueryResult("recent-messages", data, options);
}

export function queryClass_(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("class");
}

export function queryClass_Result<RowsByName extends object = TableRows>(data: unknown, options: DeclaredQueryDecodeOptions<RowsByName>): DecodedDeclaredQueryResult<typeof queries.class_, RowsByName> {
  return shunterDecodeDeclaredQueryResult("class", data, options);
}

export function querySQL2(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("sQL");
}

export function querySQL2Result<RowsByName extends object = TableRows>(data: unknown, options: DeclaredQueryDecodeOptions<RowsByName>): DecodedDeclaredQueryResult<typeof queries.sQL, RowsByName> {
  return shunterDecodeDeclaredQueryResult("sQL", data, options);
}

export const views = {
  liveMessages: "live_messages",
  liveMessages2: "live messages",
  default_: "default",
} as const;

export type ViewName = (typeof views)[keyof typeof views];

export const viewSQL = {
  liveMessages: "SELECT * FROM messages",
  liveMessages2: "SELECT * FROM messages",
  default_: "SELECT * FROM messages",
} as const;

export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];

export function subscribeLiveMessages(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {
  return subscribeDeclaredView("live_messages");
}

export function subscribeLiveMessages2(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {
  return subscribeDeclaredView("live messages");
}

export function subscribeDefault_(subscribeDeclaredView: DeclaredViewSubscriber): Promise<SubscriptionUnsubscribe> {
  return subscribeDeclaredView("default");
}

export const permissions = {
  reducers: {
    sendMessage: { required: ["messages:send"] },
    sendMessage2: { required: ["messages:send-alt"] },
    default_: { required: ["messages:send-default"] },
  },
  queries: {
    recentMessages: { required: ["messages:read"] },
    recentMessages2: { required: ["messages:read-alt"] },
    class_: { required: ["messages:read-class"] },
    sQL: { required: ["messages:read-sql"] },
  },
  views: {
    liveMessages: { required: ["messages:subscribe"] },
    liveMessages2: { required: ["messages:subscribe-alt"] },
    default_: { required: ["messages:subscribe-default"] },
  },
} as const;

export const readModels = {
  queries: {
    recentMessages: { tables: ["messages"], tags: ["history"] },
    recentMessages2: { tables: ["messages"], tags: ["history-alt"] },
    class_: { tables: ["messages"], tags: ["history-class"] },
    sQL: { tables: ["messages"], tags: ["history-sql"] },
  },
  views: {
    liveMessages: { tables: ["messages"], tags: ["realtime"] },
    liveMessages2: { tables: ["messages"], tags: ["realtime-alt"] },
    default_: { tables: ["messages"], tags: ["realtime-default"] },
  },
} as const;

