// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.
// Source contract: shunter.module_contract v1
// Module: v1_guardrails v1.0.0

export const shunterProtocol = {
  minSupportedVersion: 1,
  currentVersion: 1,
  defaultSubprotocol: "v1.bsatn.shunter",
  supportedSubprotocols: ["v1.bsatn.shunter"],
} as const;

export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];

export type ReducerCaller = (name: ReducerName, args: Uint8Array) => Promise<Uint8Array>;
export type QueryRunner = (sql: string) => Promise<Uint8Array>;
export type ViewSubscriber = (sql: string) => Promise<() => void>;
export type DeclaredQueryRunner = (name: ExecutableQueryName) => Promise<Uint8Array>;
export type DeclaredViewSubscriber = (name: ExecutableViewName) => Promise<() => void>;
export type TableRow<Name extends TableName> = TableRows[Name];
export type TableSubscriber<Row = never> = <Name extends TableName>(table: Name, onRows?: (rows: ([Row] extends [never] ? TableRow<Name> : Row)[]) => void) => Promise<() => void>;
export type UUID = string;

export interface MessagesRow {
  id: bigint;
  sender: string;
  body: string;
  sentAt: bigint;
}

export interface SysClientsRow {
  connectionId: Uint8Array;
  identity: Uint8Array;
  connectedAt: bigint;
}

export interface SysScheduledRow {
  scheduleId: bigint;
  reducerName: string;
  args: Uint8Array;
  nextRunAtNs: bigint;
  repeatNs: bigint;
}

export const tables = {
  messages: "messages",
  sysClients: "sys_clients",
  sysScheduled: "sys_scheduled",
} as const;

export type TableName = (typeof tables)[keyof typeof tables];

export type TableRows = {
  "messages": MessagesRow;
  "sys_clients": SysClientsRow;
  "sys_scheduled": SysScheduledRow;
};

export const tableReadPolicies = {
  messages: { access: "permissioned", permissions: ["messages:read"] },
  sysClients: { access: "private", permissions: [] },
  sysScheduled: { access: "private", permissions: [] },
} as const;

export const visibilityFilters = {
  ownMessages: { sql: "SELECT * FROM messages WHERE sender = :sender", returnTable: "messages", returnTableId: 0, usesCallerIdentity: true },
} as const;

export function subscribeMessages(subscribeTable: TableSubscriber<MessagesRow>): Promise<() => void> {
  return subscribeTable("messages");
}

export function subscribeSysClients(subscribeTable: TableSubscriber<SysClientsRow>): Promise<() => void> {
  return subscribeTable("sys_clients");
}

export function subscribeSysScheduled(subscribeTable: TableSubscriber<SysScheduledRow>): Promise<() => void> {
  return subscribeTable("sys_scheduled");
}

export const reducers = {
  createMessage: "create_message",
} as const;

export type ReducerName = (typeof reducers)[keyof typeof reducers];

export function callCreateMessage(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("create_message", args);
}

export const lifecycleReducers = {
  OnConnect: "OnConnect",
} as const;

export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];

export const queries = {
  recentMessages: "recent_messages",
} as const;

export type QueryName = (typeof queries)[keyof typeof queries];

export const querySQL = {
  recentMessages: "SELECT id, sender, body FROM messages ORDER BY sent_at DESC LIMIT 25",
} as const;

export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];

export function queryRecentMessages(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("recent_messages");
}

export const views = {
  liveMessageProjection: "live_message_projection",
  liveMessageCount: "live_message_count",
} as const;

export type ViewName = (typeof views)[keyof typeof views];

export const viewSQL = {
  liveMessageProjection: "SELECT id, body AS text FROM messages",
  liveMessageCount: "SELECT COUNT(*) AS n FROM messages",
} as const;

export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];

export function subscribeLiveMessageProjection(subscribeDeclaredView: DeclaredViewSubscriber): Promise<() => void> {
  return subscribeDeclaredView("live_message_projection");
}

export function subscribeLiveMessageCount(subscribeDeclaredView: DeclaredViewSubscriber): Promise<() => void> {
  return subscribeDeclaredView("live_message_count");
}

export const permissions = {
  reducers: {
    createMessage: { required: ["messages:write"] },
  },
  queries: {
    recentMessages: { required: ["messages:read"] },
  },
  views: {
    liveMessageProjection: { required: ["messages:subscribe"] },
    liveMessageCount: { required: ["messages:subscribe"] },
  },
} as const;

export const readModels = {
  queries: {
    recentMessages: { tables: ["messages"], tags: ["history", "v1"] },
  },
  views: {
    liveMessageProjection: { tables: ["messages"], tags: ["projection", "v1"] },
    liveMessageCount: { tables: ["messages"], tags: ["aggregate", "v1"] },
  },
} as const;

