// Code generated by github.com/ponchione/shunter/codegen. DO NOT EDIT.
// Source contract: shunter.module_contract v1
// Module: v1_guardrails v1.0.0

import type {
  BsatnColumn as ShunterBsatnColumn,
  DecodedDeclaredQueryResult as ShunterDecodedDeclaredQueryResult,
  DeclaredQueryDecodeOptions as ShunterDeclaredQueryDecodeOptions,
  DeclaredQueryRunner as ShunterDeclaredQueryRunner,
  DeclaredViewHandleSubscriber as ShunterDeclaredViewHandleSubscriber,
  DeclaredViewSubscriber as ShunterDeclaredViewSubscriber,
  DeclaredViewSubscriptionOptions as ShunterDeclaredViewSubscriptionOptions,
  EncodedReducerCallOptions as ShunterEncodedReducerCallOptions,
  EncodedReducerCallResultOptions as ShunterEncodedReducerCallResultOptions,
  ProtocolMetadata as ShunterProtocolMetadata,
  QueryRunner as ShunterQueryRunner,
  RawDeclaredQueryResult as ShunterRawDeclaredQueryResult,
  ReducerCaller as ShunterReducerCaller,
  ReducerCallResult as ShunterReducerCallResult,
  ReducerCallResultRequestOptions as ShunterReducerCallResultRequestOptions,
  SubscriptionUnsubscribe as ShunterSubscriptionUnsubscribe,
  SubscriptionHandle as ShunterSubscriptionHandle,
  SubscriptionHandleReturnOptions as ShunterSubscriptionHandleReturnOptions,
  TableRowDecoder as ShunterTableRowDecoder,
  TableRowDecoders as ShunterTableRowDecoders,
  TableSubscriber as ShunterTableSubscriber,
  TableSubscriptionOptions as ShunterTableSubscriptionOptions,
  ViewSubscriber as ShunterViewSubscriber,
} from "@shunter/client";

import {
  callReducerWithEncodedArgs as shunterCallReducerWithEncodedArgs,
  callReducerWithResult as shunterCallReducerWithResult,
  decodeBsatnProduct as shunterDecodeBsatnProduct,
  decodeDeclaredQueryResult as shunterDecodeDeclaredQueryResult,
  encodeBsatnProduct as shunterEncodeBsatnProduct,
} from "@shunter/client";

export const shunterProtocol = {
  minSupportedVersion: 1,
  currentVersion: 1,
  defaultSubprotocol: "v1.bsatn.shunter",
  supportedSubprotocols: ["v1.bsatn.shunter"],
} as const satisfies ShunterProtocolMetadata;

export type ShunterSubprotocol = (typeof shunterProtocol.supportedSubprotocols)[number];

export type ReducerCaller = ShunterReducerCaller<ReducerName, Uint8Array, Uint8Array>;
export type EncodedReducerCallOptions<Args = unknown> = ShunterEncodedReducerCallOptions<Args>;
export type EncodedReducerCallResultOptions<Args = unknown, Result = Uint8Array> = ShunterEncodedReducerCallResultOptions<Args, Result>;
export type ReducerCallResult<Name extends ReducerName = ReducerName, Result = Uint8Array> = ShunterReducerCallResult<Name, Result>;
export type ReducerCallResultOptions = ShunterReducerCallResultRequestOptions<Uint8Array>;
export type QueryRunner = ShunterQueryRunner<Uint8Array>;
export type ViewSubscriber = ShunterViewSubscriber;
export type DeclaredQueryRunner = ShunterDeclaredQueryRunner<ExecutableQueryName, Uint8Array>;
export type RawDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName> = ShunterRawDeclaredQueryResult<Name>;
export type DeclaredQueryDecodeOptions<RowsByName extends object = TableRows> = ShunterDeclaredQueryDecodeOptions<RowsByName>;
export type DecodedDeclaredQueryResult<Name extends ExecutableQueryName = ExecutableQueryName, RowsByName extends object = TableRows> = ShunterDecodedDeclaredQueryResult<Name, RowsByName>;
export type DeclaredViewSubscriber = ShunterDeclaredViewSubscriber<ExecutableViewName>;
export type DeclaredViewHandleSubscriber = ShunterDeclaredViewHandleSubscriber<ExecutableViewName>;
export type DeclaredViewSubscriptionOptions<Row = unknown> = ShunterDeclaredViewSubscriptionOptions<Row>;
export type SubscriptionUnsubscribe = ShunterSubscriptionUnsubscribe;
export type SubscriptionHandle<Row = unknown> = ShunterSubscriptionHandle<Row>;
export type SubscriptionHandleReturnOptions = ShunterSubscriptionHandleReturnOptions;
export type TableRow<Name extends TableName> = TableRows[Name];
export type TableSubscriber<Row = never> = ShunterTableSubscriber<TableName, TableRows, Row>;
export type TableSubscriptionOptions<Row = unknown> = ShunterTableSubscriptionOptions<Row>;
export type TableRowDecoder<Name extends TableName> = ShunterTableRowDecoder<TableRows[Name]>;
export type TableRowDecoders<RowsByName extends object = TableRows> = ShunterTableRowDecoders<RowsByName>;
export type UUID = string;

export interface MessagesRow {
  id: bigint;
  sender: string;
  topic: string | null;
  body: string;
  sentAt: bigint;
}

export interface SysClientsRow {
  connectionId: Uint8Array;
  identity: Uint8Array;
  connectedAt: bigint;
}

export interface SysScheduledRow {
  scheduleId: bigint;
  reducerName: string;
  args: Uint8Array;
  nextRunAtNs: bigint;
  repeatNs: bigint;
}

export const tables = {
  messages: "messages",
  sysClients: "sys_clients",
  sysScheduled: "sys_scheduled",
} as const;

export type TableName = (typeof tables)[keyof typeof tables];

export type TableRows = {
  "messages": MessagesRow;
  "sys_clients": SysClientsRow;
  "sys_scheduled": SysScheduledRow;
};

const messagesColumns = [
  { name: "id", kind: "uint64" },
  { name: "sender", kind: "string" },
  { name: "topic", kind: "string", nullable: true },
  { name: "body", kind: "string" },
  { name: "sent_at", kind: "timestamp" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeMessagesRow(row: Uint8Array): MessagesRow {
  return shunterDecodeBsatnProduct(row, messagesColumns, (values) => ({
    id: values[0] as bigint,
    sender: values[1] as string,
    topic: values[2] as string | null,
    body: values[3] as string,
    sentAt: values[4] as bigint,
  }));
}

const sysClientsColumns = [
  { name: "connection_id", kind: "bytes" },
  { name: "identity", kind: "bytes" },
  { name: "connected_at", kind: "int64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeSysClientsRow(row: Uint8Array): SysClientsRow {
  return shunterDecodeBsatnProduct(row, sysClientsColumns, (values) => ({
    connectionId: values[0] as Uint8Array,
    identity: values[1] as Uint8Array,
    connectedAt: values[2] as bigint,
  }));
}

const sysScheduledColumns = [
  { name: "schedule_id", kind: "uint64" },
  { name: "reducer_name", kind: "string" },
  { name: "args", kind: "bytes" },
  { name: "next_run_at_ns", kind: "int64" },
  { name: "repeat_ns", kind: "int64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeSysScheduledRow(row: Uint8Array): SysScheduledRow {
  return shunterDecodeBsatnProduct(row, sysScheduledColumns, (values) => ({
    scheduleId: values[0] as bigint,
    reducerName: values[1] as string,
    args: values[2] as Uint8Array,
    nextRunAtNs: values[3] as bigint,
    repeatNs: values[4] as bigint,
  }));
}

export const tableRowDecoders = {
  "messages": decodeMessagesRow,
  "sys_clients": decodeSysClientsRow,
  "sys_scheduled": decodeSysScheduledRow,
} as const satisfies TableRowDecoders;

export const tableReadPolicies = {
  messages: { access: "permissioned", permissions: ["messages:read"] },
  sysClients: { access: "private", permissions: [] },
  sysScheduled: { access: "private", permissions: [] },
} as const;

export const visibilityFilters = {
  ownMessages: { sql: "SELECT * FROM messages WHERE sender = :sender", returnTable: "messages", returnTableId: 0, usesCallerIdentity: true },
} as const;

export function subscribeMessages(subscribeTable: TableSubscriber<MessagesRow>, onRows?: (rows: MessagesRow[]) => void, options: TableSubscriptionOptions<MessagesRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<MessagesRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["messages"] } : options;
  return subscribeTable("messages", onRows, subscribeOptions);
}

export function subscribeSysClients(subscribeTable: TableSubscriber<SysClientsRow>, onRows?: (rows: SysClientsRow[]) => void, options: TableSubscriptionOptions<SysClientsRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<SysClientsRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["sys_clients"] } : options;
  return subscribeTable("sys_clients", onRows, subscribeOptions);
}

export function subscribeSysScheduled(subscribeTable: TableSubscriber<SysScheduledRow>, onRows?: (rows: SysScheduledRow[]) => void, options: TableSubscriptionOptions<SysScheduledRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: TableSubscriptionOptions<SysScheduledRow> = options.decodeRow === undefined ? { ...options, decodeRow: tableRowDecoders["sys_scheduled"] } : options;
  return subscribeTable("sys_scheduled", onRows, subscribeOptions);
}

export const reducers = {
  createMessage: "create_message",
} as const;

export type ReducerName = (typeof reducers)[keyof typeof reducers];

export interface CreateMessageArgs {
  sender: string;
  body: string;
}

const createMessageArgsColumns = [
  { name: "sender", kind: "string" },
  { name: "body", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function encodeCreateMessageArgs(value: CreateMessageArgs): Uint8Array {
  return shunterEncodeBsatnProduct([
    value.sender,
    value.body,
  ], createMessageArgsColumns);
}

export interface CreateMessageResult {
  messageId: bigint;
}

const createMessageResultColumns = [
  { name: "message_id", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeCreateMessageResult(row: Uint8Array): CreateMessageResult {
  return shunterDecodeBsatnProduct(row, createMessageResultColumns, (values) => ({
    messageId: values[0] as bigint,
  }));
}

export function callCreateMessage(callReducer: ReducerCaller, args: Uint8Array): Promise<Uint8Array> {
  return callReducer("create_message", args);
}

export function callCreateMessageTyped(callReducer: ReducerCaller, args: CreateMessageArgs, options: EncodedReducerCallOptions<CreateMessageArgs> = {}): Promise<Uint8Array> {
  const callOptions: EncodedReducerCallOptions<CreateMessageArgs> = options.encodeArgs === undefined ? { ...options, encodeArgs: encodeCreateMessageArgs } : options;
  return shunterCallReducerWithEncodedArgs(callReducer, "create_message", args, callOptions);
}

export function callCreateMessageResult(callReducer: ReducerCaller, args: Uint8Array, options: ReducerCallResultOptions = {}): Promise<ReducerCallResult<typeof reducers.createMessage>> {
  return shunterCallReducerWithResult(callReducer, "create_message", args, options);
}

export const lifecycleReducers = {
  OnConnect: "OnConnect",
} as const;

export type LifecycleReducerName = (typeof lifecycleReducers)[keyof typeof lifecycleReducers];

export const queries = {
  recentMessages: "recent_messages",
} as const;

export type QueryName = (typeof queries)[keyof typeof queries];

export const querySQL = {
  recentMessages: "SELECT id, sender, body FROM messages ORDER BY sent_at DESC LIMIT 25",
} as const;

export type ExecutableQueryName = (typeof queries)[keyof typeof querySQL];

export interface RecentMessagesQueryRow {
  id: bigint;
  sender: string;
  body: string;
}

const recentMessagesQueryColumns = [
  { name: "id", kind: "uint64" },
  { name: "sender", kind: "string" },
  { name: "body", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeRecentMessagesQueryRow(row: Uint8Array): RecentMessagesQueryRow {
  return shunterDecodeBsatnProduct(row, recentMessagesQueryColumns, (values) => ({
    id: values[0] as bigint,
    sender: values[1] as string,
    body: values[2] as string,
  }));
}

export type RecentMessagesQueryRows = {
  "messages": RecentMessagesQueryRow;
};

export const recentMessagesQueryRowDecoders = {
  "messages": decodeRecentMessagesQueryRow,
} as const satisfies TableRowDecoders<RecentMessagesQueryRows>;

export function queryRecentMessages(runDeclaredQuery: DeclaredQueryRunner): Promise<Uint8Array> {
  return runDeclaredQuery("recent_messages");
}

export function queryRecentMessagesResult(data: unknown, options: DeclaredQueryDecodeOptions<RecentMessagesQueryRows> = {}): DecodedDeclaredQueryResult<typeof queries.recentMessages, RecentMessagesQueryRows> {
  const decodeOptions: DeclaredQueryDecodeOptions<RecentMessagesQueryRows> = options.tableDecoders === undefined && options.decodeRow === undefined ? { ...options, tableDecoders: recentMessagesQueryRowDecoders } : options;
  return shunterDecodeDeclaredQueryResult("recent_messages", data, decodeOptions);
}

export async function queryRecentMessagesDecoded(runDeclaredQuery: DeclaredQueryRunner, options: DeclaredQueryDecodeOptions<RecentMessagesQueryRows> = {}): Promise<DecodedDeclaredQueryResult<typeof queries.recentMessages, RecentMessagesQueryRows>> {
  return queryRecentMessagesResult(await runDeclaredQuery("recent_messages"), options);
}

export const views = {
  liveMessageProjection: "live_message_projection",
  liveMessageCount: "live_message_count",
} as const;

export type ViewName = (typeof views)[keyof typeof views];

export const viewSQL = {
  liveMessageProjection: "SELECT id, body AS text FROM messages",
  liveMessageCount: "SELECT COUNT(*) AS n FROM messages",
} as const;

export type ExecutableViewName = (typeof views)[keyof typeof viewSQL];

export interface LiveMessageProjectionViewRow {
  id: bigint;
  text: string;
}

const liveMessageProjectionViewColumns = [
  { name: "id", kind: "uint64" },
  { name: "text", kind: "string" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeLiveMessageProjectionViewRow(row: Uint8Array): LiveMessageProjectionViewRow {
  return shunterDecodeBsatnProduct(row, liveMessageProjectionViewColumns, (values) => ({
    id: values[0] as bigint,
    text: values[1] as string,
  }));
}

export function subscribeLiveMessageProjection(subscribeDeclaredView: DeclaredViewSubscriber, options: DeclaredViewSubscriptionOptions<LiveMessageProjectionViewRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: DeclaredViewSubscriptionOptions<LiveMessageProjectionViewRow> = options.decodeRow === undefined ? { ...options, decodeRow: decodeLiveMessageProjectionViewRow } : options;
  return subscribeDeclaredView("live_message_projection", subscribeOptions);
}

export function subscribeLiveMessageProjectionHandle(subscribeDeclaredView: DeclaredViewHandleSubscriber, options: DeclaredViewSubscriptionOptions<LiveMessageProjectionViewRow> & SubscriptionHandleReturnOptions): Promise<SubscriptionHandle<LiveMessageProjectionViewRow>> {
  const subscribeOptions: DeclaredViewSubscriptionOptions<LiveMessageProjectionViewRow> & SubscriptionHandleReturnOptions = options.decodeRow === undefined ? { ...options, decodeRow: decodeLiveMessageProjectionViewRow } : options;
  return subscribeDeclaredView("live_message_projection", subscribeOptions);
}

export interface LiveMessageCountViewRow {
  n: bigint;
}

const liveMessageCountViewColumns = [
  { name: "n", kind: "uint64" },
] as const satisfies readonly ShunterBsatnColumn[];

export function decodeLiveMessageCountViewRow(row: Uint8Array): LiveMessageCountViewRow {
  return shunterDecodeBsatnProduct(row, liveMessageCountViewColumns, (values) => ({
    n: values[0] as bigint,
  }));
}

export function subscribeLiveMessageCount(subscribeDeclaredView: DeclaredViewSubscriber, options: DeclaredViewSubscriptionOptions<LiveMessageCountViewRow> = {}): Promise<SubscriptionUnsubscribe> {
  const subscribeOptions: DeclaredViewSubscriptionOptions<LiveMessageCountViewRow> = options.decodeRow === undefined ? { ...options, decodeRow: decodeLiveMessageCountViewRow } : options;
  return subscribeDeclaredView("live_message_count", subscribeOptions);
}

export function subscribeLiveMessageCountHandle(subscribeDeclaredView: DeclaredViewHandleSubscriber, options: DeclaredViewSubscriptionOptions<LiveMessageCountViewRow> & SubscriptionHandleReturnOptions): Promise<SubscriptionHandle<LiveMessageCountViewRow>> {
  const subscribeOptions: DeclaredViewSubscriptionOptions<LiveMessageCountViewRow> & SubscriptionHandleReturnOptions = options.decodeRow === undefined ? { ...options, decodeRow: decodeLiveMessageCountViewRow } : options;
  return subscribeDeclaredView("live_message_count", subscribeOptions);
}

export const permissions = {
  reducers: {
    createMessage: { required: ["messages:write"] },
  },
  queries: {
    recentMessages: { required: ["messages:read"] },
  },
  views: {
    liveMessageProjection: { required: ["messages:subscribe"] },
    liveMessageCount: { required: ["messages:subscribe"] },
  },
} as const;

export const readModels = {
  queries: {
    recentMessages: { tables: ["messages"], tags: ["history", "v1"] },
  },
  views: {
    liveMessageProjection: { tables: ["messages"], tags: ["projection", "v1"] },
    liveMessageCount: { tables: ["messages"], tags: ["aggregate", "v1"] },
  },
} as const;

